# Generated by Django 2.1.4 on 2019-03-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscarsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CeccEvent',
        ),
        migrations.DeleteModel(
            name='Ceccmenu',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
