# Generated by Django 2.1.4 on 2020-01-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscarsapp', '0002_auto_20190304_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oscarballot',
            name='actor',
            field=models.CharField(choices=[('Antonio Banderas', 'Antonio Banderas'), ('Leonardo DiCaprio', 'Leonardo DiCaprio'), ('Adam Driver', 'Adam Driver'), ('Joaquin Phoenix', 'Joaquin Phoenix'), ('Jonathan Pryce', 'Jonathan Pryce')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='actress',
            field=models.CharField(choices=[('Cynthia Erivo', 'Cynthia Erivo'), ('Scarlett Johansson', 'Scarlett Johansson'), ('Saoirse Ronan', 'Saoirse Ronan'), ('Charlize Theron', 'Charlize Theron'), ('Renee Zellweger', 'Renee Zellweger')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='animatedfeature',
            field=models.CharField(choices=[('How to Train Your Dragon: The Hidden World', 'How to Train Your Dragon: The Hidden World'), ('I Lost My Body', 'I Lost My Body'), ('Klaus', 'Klaus'), ('Missing Link', 'Missing Link'), ('Toy Story 4', 'Toy Story 4')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='animatedshort',
            field=models.CharField(choices=[('Dcera (Daughter)', 'Dcera (Daughter)'), ('Hair Love', 'Hair Love'), ('Kitbull', 'Kitbull'), ('Memorable', 'Memorable'), ('Sister', 'Sister')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='bestpicture',
            field=models.CharField(choices=[('Ford v Ferrari', 'Ford v Ferrari'), ('The Irishman', 'The Irishman'), ('Jojo Rabbit', 'Jojo Rabbit'), ('Joker', 'Joker'), ('Little Women', 'Little Women'), ('Marriage Story', 'Marriage Story'), ('1917', '1917'), ('Once upon a Time... in Hollywood', 'Once upon a Time... in Hollywood'), ('Parasite', 'Parasite')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='cinematography',
            field=models.CharField(choices=[('The Irishman', 'The Irishman'), ('Joker', 'Joker'), ('The Lighthouse', 'The Lighthouse'), ('1917', '1917'), ('Once upon a Time... in Hollywood', 'Once upon a Time... in Hollywood')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='costume',
            field=models.CharField(choices=[('The Irishman', 'The Irishman'), ('Jojo Rabbit', 'Jojo Rabbit'), ('Joker', 'Joker'), ('Little Women', 'Little Women'), ('Once upon a Time... in Hollywood', 'Once upon a Time... in Hollywood')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='directing',
            field=models.CharField(choices=[('Martin Scorsese', 'Martin Scorsese'), ('Todd Phillips', 'Todd Phillips'), ('Sam Mendes', 'Sam Mendes'), ('Quentin Tarantino', 'Quentin Tarantino'), ('Bong Joon Ho', 'Bong Joon Ho')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='docshort',
            field=models.CharField(choices=[('In the Absence', 'In the Absence'), ("Learning to Skateboard in a Warzone (If You're a Girl)", "Learning to Skateboard in a Warzone (If You're a Girl)"), ('Life Overtakes Me', 'Life Overtakes Me'), ('St. Louis Superman', 'St. Louis Superman'), ('Walk Run Cha-Cha', 'Walk Run Cha-Cha')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='documentary',
            field=models.CharField(choices=[('American Factory', 'American Factory'), ('The Cave', 'The Cave'), ('The Edge of Democracy', 'The Edge of Democracy'), ('For Sama', 'For Sama'), ('Honeyland', 'Honeyland')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='fediting',
            field=models.CharField(choices=[('Ford v Ferrari', 'Ford v Ferrari'), ('The Irishman', 'The Irishman'), ('Jojo Rabbit', 'Jojo Rabbit'), ('Joker', 'Joker'), ('Parasite', 'Parasite')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='foreign',
            field=models.CharField(choices=[('Corpus Christi', 'Corpus Christi'), ('Honeyland', 'Honeyland'), ('Les Misérables', 'Les Misérables'), ('Pain and Glory', 'Pain and Glory'), ('Parasite', 'Parasite')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='makeupandh',
            field=models.CharField(choices=[('Bombshell', 'Bombshell'), ('Joker', 'Joker'), ('Judy', 'Judy'), ('Maleficent: Mistress of Evil', 'Maleficent: Mistress of Evil'), ('1917', '1917')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='mscore',
            field=models.CharField(choices=[('Joker', 'Joker'), ('Little Women', 'Little Women'), ('Marriage Story', 'Marriage Story'), ('1917', '1917'), ('Star Wars: The Rise of Skywalker', 'Star Wars: The Rise of Skywalker')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='msong',
            field=models.CharField(choices=[('I Can’t Let You Throw Yourself Away', 'I Can’t Let You Throw Yourself Away'), ("(I'm Gonna) Love Me Again", "(I'm Gonna) Love Me Again"), ("I'm Standing With You", "I'm Standing With You"), ('Into the Unknown', 'Into the Unknown'), ('Stand Up', 'Stand Up')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='prodesign',
            field=models.CharField(choices=[('The Irishman', 'The Irishman'), ('Jojo Rabbit', 'Jojo Rabbit'), ('1917', '1917'), ('Once upon a Time... in Hollywood', 'Once upon a Time... in Hollywood'), ('Parasite', 'Parasite')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='sediting',
            field=models.CharField(choices=[('Ford v Ferrari', 'Ford v Ferrari'), ('Joker', 'Joker'), ('1917', '1917'), ('Once upon a Time... in Hollywood', 'Once upon a Time... in Hollywood'), ('Star Wars: The Rise of Skywalker', 'Star Wars: The Rise of Skywalker')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='shortfilm',
            field=models.CharField(choices=[('Brotherhood', 'Brotherhood'), ('Nefta Football Club', 'Nefta Football Club'), ("The Neighbors' Window", "The Neighbors' Window"), ('Saria', 'Saria'), ('A Sister', 'A Sister')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='smixing',
            field=models.CharField(choices=[('Ad Astra', 'Ad Astra'), ('Ford v Ferrari', 'Ford v Ferrari'), ('Joker', 'Joker'), ('1917', '1917'), ('Once upon a Time... in Hollywood', 'Once upon a Time... in Hollywood')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='supactor',
            field=models.CharField(choices=[('Tom Hanks', 'Tom Hanks'), ('Anthony Hopkins', 'Anthony Hopkins'), ('Al Pacino', 'Al Pacino'), ('Joe Pesci', 'Joe Pesci'), ('Brad Pitt', 'Brad Pitt')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='supactress',
            field=models.CharField(choices=[('Kathy Bates', 'Kathy Bates'), ('Laura Dern', 'Laura Dern'), ('Scarlett Johansson', 'Scarlett Johansson'), ('Florence Pugh', 'Florence Pugh'), ('Margot Robbie', 'Margot Robbie')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='visualfx',
            field=models.CharField(choices=[('Avengers: Endgame', 'Avengers: Endgame'), ('The Irishman', 'The Irishman'), ('The Lion King', 'The Lion King'), ('1917', '1917'), ('Star Wars: The Rise of Skywalker', 'Star Wars: The Rise of Skywalker')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='writingad',
            field=models.CharField(choices=[('The Irishman', 'The Irishman'), ('Jojo Rabbit', 'Jojo Rabbit'), ('Joker', 'Joker'), ('Little Women', 'Little Women'), ('The Two Popes', 'The Two Popes')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='writingor',
            field=models.CharField(choices=[('Knives Out', 'Knives Out'), ('Marriage Story', 'Marriage Story'), ('1917', '1917'), ('Once upon a Time... in Hollywood', 'Once upon a Time... in Hollywood'), ('Parasite', 'Parasite')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='actor',
            field=models.CharField(choices=[('Antonio Banderas', 'Antonio Banderas'), ('Leonardo DiCaprio', 'Leonardo DiCaprio'), ('Adam Driver', 'Adam Driver'), ('Joaquin Phoenix', 'Joaquin Phoenix'), ('Jonathan Pryce', 'Jonathan Pryce')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='actress',
            field=models.CharField(choices=[('Cynthia Erivo', 'Cynthia Erivo'), ('Scarlett Johansson', 'Scarlett Johansson'), ('Saoirse Ronan', 'Saoirse Ronan'), ('Charlize Theron', 'Charlize Theron'), ('Renee Zellweger', 'Renee Zellweger')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='animatedfeature',
            field=models.CharField(choices=[('How to Train Your Dragon: The Hidden World', 'How to Train Your Dragon: The Hidden World'), ('I Lost My Body', 'I Lost My Body'), ('Klaus', 'Klaus'), ('Missing Link', 'Missing Link'), ('Toy Story 4', 'Toy Story 4')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='animatedshort',
            field=models.CharField(choices=[('Dcera (Daughter)', 'Dcera (Daughter)'), ('Hair Love', 'Hair Love'), ('Kitbull', 'Kitbull'), ('Memorable', 'Memorable'), ('Sister', 'Sister')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='bestpicture',
            field=models.CharField(choices=[('Ford v Ferrari', 'Ford v Ferrari'), ('The Irishman', 'The Irishman'), ('Jojo Rabbit', 'Jojo Rabbit'), ('Joker', 'Joker'), ('Little Women', 'Little Women'), ('Marriage Story', 'Marriage Story'), ('1917', '1917'), ('Once upon a Time... in Hollywood', 'Once upon a Time... in Hollywood'), ('Parasite', 'Parasite')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='cinematography',
            field=models.CharField(choices=[('The Irishman', 'The Irishman'), ('Joker', 'Joker'), ('The Lighthouse', 'The Lighthouse'), ('1917', '1917'), ('Once upon a Time... in Hollywood', 'Once upon a Time... in Hollywood')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='costume',
            field=models.CharField(choices=[('The Irishman', 'The Irishman'), ('Jojo Rabbit', 'Jojo Rabbit'), ('Joker', 'Joker'), ('Little Women', 'Little Women'), ('Once upon a Time... in Hollywood', 'Once upon a Time... in Hollywood')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='directing',
            field=models.CharField(choices=[('Martin Scorsese', 'Martin Scorsese'), ('Todd Phillips', 'Todd Phillips'), ('Sam Mendes', 'Sam Mendes'), ('Quentin Tarantino', 'Quentin Tarantino'), ('Bong Joon Ho', 'Bong Joon Ho')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='docshort',
            field=models.CharField(choices=[('In the Absence', 'In the Absence'), ("Learning to Skateboard in a Warzone (If You're a Girl)", "Learning to Skateboard in a Warzone (If You're a Girl)"), ('Life Overtakes Me', 'Life Overtakes Me'), ('St. Louis Superman', 'St. Louis Superman'), ('Walk Run Cha-Cha', 'Walk Run Cha-Cha')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='documentary',
            field=models.CharField(choices=[('American Factory', 'American Factory'), ('The Cave', 'The Cave'), ('The Edge of Democracy', 'The Edge of Democracy'), ('For Sama', 'For Sama'), ('Honeyland', 'Honeyland')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='fediting',
            field=models.CharField(choices=[('Ford v Ferrari', 'Ford v Ferrari'), ('The Irishman', 'The Irishman'), ('Jojo Rabbit', 'Jojo Rabbit'), ('Joker', 'Joker'), ('Parasite', 'Parasite')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='foreign',
            field=models.CharField(choices=[('Corpus Christi', 'Corpus Christi'), ('Honeyland', 'Honeyland'), ('Les Misérables', 'Les Misérables'), ('Pain and Glory', 'Pain and Glory'), ('Parasite', 'Parasite')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='makeupandh',
            field=models.CharField(choices=[('Bombshell', 'Bombshell'), ('Joker', 'Joker'), ('Judy', 'Judy'), ('Maleficent: Mistress of Evil', 'Maleficent: Mistress of Evil'), ('1917', '1917')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='mscore',
            field=models.CharField(choices=[('Joker', 'Joker'), ('Little Women', 'Little Women'), ('Marriage Story', 'Marriage Story'), ('1917', '1917'), ('Star Wars: The Rise of Skywalker', 'Star Wars: The Rise of Skywalker')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='msong',
            field=models.CharField(choices=[('I Can’t Let You Throw Yourself Away', 'I Can’t Let You Throw Yourself Away'), ("(I'm Gonna) Love Me Again", "(I'm Gonna) Love Me Again"), ("I'm Standing With You", "I'm Standing With You"), ('Into the Unknown', 'Into the Unknown'), ('Stand Up', 'Stand Up')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='prodesign',
            field=models.CharField(choices=[('The Irishman', 'The Irishman'), ('Jojo Rabbit', 'Jojo Rabbit'), ('1917', '1917'), ('Once upon a Time... in Hollywood', 'Once upon a Time... in Hollywood'), ('Parasite', 'Parasite')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='sediting',
            field=models.CharField(choices=[('Ford v Ferrari', 'Ford v Ferrari'), ('Joker', 'Joker'), ('1917', '1917'), ('Once upon a Time... in Hollywood', 'Once upon a Time... in Hollywood'), ('Star Wars: The Rise of Skywalker', 'Star Wars: The Rise of Skywalker')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='shortfilm',
            field=models.CharField(choices=[('Brotherhood', 'Brotherhood'), ('Nefta Football Club', 'Nefta Football Club'), ("The Neighbors' Window", "The Neighbors' Window"), ('Saria', 'Saria'), ('A Sister', 'A Sister')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='smixing',
            field=models.CharField(choices=[('Ad Astra', 'Ad Astra'), ('Ford v Ferrari', 'Ford v Ferrari'), ('Joker', 'Joker'), ('1917', '1917'), ('Once upon a Time... in Hollywood', 'Once upon a Time... in Hollywood')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='supactor',
            field=models.CharField(choices=[('Tom Hanks', 'Tom Hanks'), ('Anthony Hopkins', 'Anthony Hopkins'), ('Al Pacino', 'Al Pacino'), ('Joe Pesci', 'Joe Pesci'), ('Brad Pitt', 'Brad Pitt')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='supactress',
            field=models.CharField(choices=[('Kathy Bates', 'Kathy Bates'), ('Laura Dern', 'Laura Dern'), ('Scarlett Johansson', 'Scarlett Johansson'), ('Florence Pugh', 'Florence Pugh'), ('Margot Robbie', 'Margot Robbie')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='visualfx',
            field=models.CharField(choices=[('Avengers: Endgame', 'Avengers: Endgame'), ('The Irishman', 'The Irishman'), ('The Lion King', 'The Lion King'), ('1917', '1917'), ('Star Wars: The Rise of Skywalker', 'Star Wars: The Rise of Skywalker')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='writingad',
            field=models.CharField(choices=[('The Irishman', 'The Irishman'), ('Jojo Rabbit', 'Jojo Rabbit'), ('Joker', 'Joker'), ('Little Women', 'Little Women'), ('The Two Popes', 'The Two Popes')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='writingor',
            field=models.CharField(choices=[('Knives Out', 'Knives Out'), ('Marriage Story', 'Marriage Story'), ('1917', '1917'), ('Once upon a Time... in Hollywood', 'Once upon a Time... in Hollywood'), ('Parasite', 'Parasite')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='actor',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Antonio Banderas', 'Antonio Banderas'), ('Leonardo DiCaprio', 'Leonardo DiCaprio'), ('Adam Driver', 'Adam Driver'), ('Joaquin Phoenix', 'Joaquin Phoenix'), ('Jonathan Pryce', 'Jonathan Pryce')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='actress',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Cynthia Erivo', 'Cynthia Erivo'), ('Scarlett Johansson', 'Scarlett Johansson'), ('Saoirse Ronan', 'Saoirse Ronan'), ('Charlize Theron', 'Charlize Theron'), ('Renee Zellweger', 'Renee Zellweger')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='animatedfeature',
            field=models.CharField(choices=[('TBD', 'TBD'), ('How to Train Your Dragon: The Hidden World', 'How to Train Your Dragon: The Hidden World'), ('I Lost My Body', 'I Lost My Body'), ('Klaus', 'Klaus'), ('Missing Link', 'Missing Link'), ('Toy Story 4', 'Toy Story 4')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='animatedshort',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Dcera (Daughter)', 'Dcera (Daughter)'), ('Hair Love', 'Hair Love'), ('Kitbull', 'Kitbull'), ('Memorable', 'Memorable'), ('Sister', 'Sister')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='bestpicture',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Ford v Ferrari', 'Ford v Ferrari'), ('The Irishman', 'The Irishman'), ('Jojo Rabbit', 'Jojo Rabbit'), ('Joker', 'Joker'), ('Little Women', 'Little Women'), ('Marriage Story', 'Marriage Story'), ('1917', '1917'), ('Once upon a Time... in Hollywood', 'Once upon a Time... in Hollywood'), ('Parasite', 'Parasite')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='cinematography',
            field=models.CharField(choices=[('TBD', 'TBD'), ('The Irishman', 'The Irishman'), ('Joker', 'Joker'), ('The Lighthouse', 'The Lighthouse'), ('1917', '1917'), ('Once upon a Time... in Hollywood', 'Once upon a Time... in Hollywood')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='costume',
            field=models.CharField(choices=[('TBD', 'TBD'), ('The Irishman', 'The Irishman'), ('Jojo Rabbit', 'Jojo Rabbit'), ('Joker', 'Joker'), ('Little Women', 'Little Women'), ('Once upon a Time... in Hollywood', 'Once upon a Time... in Hollywood')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='directing',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Martin Scorsese', 'Martin Scorsese'), ('Todd Phillips', 'Todd Phillips'), ('Sam Mendes', 'Sam Mendes'), ('Quentin Tarantino', 'Quentin Tarantino'), ('Bong Joon Ho', 'Bong Joon Ho')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='docshort',
            field=models.CharField(choices=[('TBD', 'TBD'), ('In the Absence', 'In the Absence'), ("Learning to Skateboard in a Warzone (If You're a Girl)", "Learning to Skateboard in a Warzone (If You're a Girl)"), ('Life Overtakes Me', 'Life Overtakes Me'), ('St. Louis Superman', 'St. Louis Superman'), ('Walk Run Cha-Cha', 'Walk Run Cha-Cha')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='documentary',
            field=models.CharField(choices=[('TBD', 'TBD'), ('American Factory', 'American Factory'), ('The Cave', 'The Cave'), ('The Edge of Democracy', 'The Edge of Democracy'), ('For Sama', 'For Sama'), ('Honeyland', 'Honeyland')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='fediting',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Ford v Ferrari', 'Ford v Ferrari'), ('The Irishman', 'The Irishman'), ('Jojo Rabbit', 'Jojo Rabbit'), ('Joker', 'Joker'), ('Parasite', 'Parasite')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='foreign',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Corpus Christi', 'Corpus Christi'), ('Honeyland', 'Honeyland'), ('Les Misérables', 'Les Misérables'), ('Pain and Glory', 'Pain and Glory'), ('Parasite', 'Parasite')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='makeupandh',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Bombshell', 'Bombshell'), ('Joker', 'Joker'), ('Judy', 'Judy'), ('Maleficent: Mistress of Evil', 'Maleficent: Mistress of Evil'), ('1917', '1917')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='mscore',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Joker', 'Joker'), ('Little Women', 'Little Women'), ('Marriage Story', 'Marriage Story'), ('1917', '1917'), ('Star Wars: The Rise of Skywalker', 'Star Wars: The Rise of Skywalker')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='msong',
            field=models.CharField(choices=[('TBD', 'TBD'), ('I Can’t Let You Throw Yourself Away', 'I Can’t Let You Throw Yourself Away'), ("(I'm Gonna) Love Me Again", "(I'm Gonna) Love Me Again"), ("I'm Standing With You", "I'm Standing With You"), ('Into the Unknown', 'Into the Unknown'), ('Stand Up', 'Stand Up')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='prodesign',
            field=models.CharField(choices=[('TBD', 'TBD'), ('The Irishman', 'The Irishman'), ('Jojo Rabbit', 'Jojo Rabbit'), ('1917', '1917'), ('Once upon a Time... in Hollywood', 'Once upon a Time... in Hollywood'), ('Parasite', 'Parasite')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='sediting',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Ford v Ferrari', 'Ford v Ferrari'), ('Joker', 'Joker'), ('1917', '1917'), ('Once upon a Time... in Hollywood', 'Once upon a Time... in Hollywood'), ('Star Wars: The Rise of Skywalker', 'Star Wars: The Rise of Skywalker')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='shortfilm',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Brotherhood', 'Brotherhood'), ('Nefta Football Club', 'Nefta Football Club'), ("The Neighbors' Window", "The Neighbors' Window"), ('Saria', 'Saria'), ('A Sister', 'A Sister')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='smixing',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Ad Astra', 'Ad Astra'), ('Ford v Ferrari', 'Ford v Ferrari'), ('Joker', 'Joker'), ('1917', '1917'), ('Once upon a Time... in Hollywood', 'Once upon a Time... in Hollywood')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='supactor',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Tom Hanks', 'Tom Hanks'), ('Anthony Hopkins', 'Anthony Hopkins'), ('Al Pacino', 'Al Pacino'), ('Joe Pesci', 'Joe Pesci'), ('Brad Pitt', 'Brad Pitt')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='supactress',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Kathy Bates', 'Kathy Bates'), ('Laura Dern', 'Laura Dern'), ('Scarlett Johansson', 'Scarlett Johansson'), ('Florence Pugh', 'Florence Pugh'), ('Margot Robbie', 'Margot Robbie')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='visualfx',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Avengers: Endgame', 'Avengers: Endgame'), ('The Irishman', 'The Irishman'), ('The Lion King', 'The Lion King'), ('1917', '1917'), ('Star Wars: The Rise of Skywalker', 'Star Wars: The Rise of Skywalker')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='writingad',
            field=models.CharField(choices=[('TBD', 'TBD'), ('The Irishman', 'The Irishman'), ('Jojo Rabbit', 'Jojo Rabbit'), ('Joker', 'Joker'), ('Little Women', 'Little Women'), ('The Two Popes', 'The Two Popes')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='writingor',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Knives Out', 'Knives Out'), ('Marriage Story', 'Marriage Story'), ('1917', '1917'), ('Once upon a Time... in Hollywood', 'Once upon a Time... in Hollywood'), ('Parasite', 'Parasite')], default='NA', max_length=100),
        ),
    ]
