# Generated by Django 2.1.4 on 2020-08-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscarsapp', '0003_auto_20200128_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oscarballot',
            old_name='name',
            new_name='name2',
        ),
    ]
