# Generated by Django 2.1.4 on 2020-08-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscarsapp', '0004_auto_20200822_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oscarballot',
            old_name='name2',
            new_name='name',
        ),
    ]
