# Generated by Django 2.1.4 on 2021-04-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscarsapp', '0005_auto_20200822_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='winners',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='actor',
            field=models.CharField(choices=[('Riz Ahmed', 'Riz Ahmed'), ('Chadwick Boseman', 'Chadwick Boseman'), ('Anthony Hopkins', 'Anthony Hopkins'), ('Gary Oldman', 'Gary Oldman'), ('Steven Yeun', 'Steven Yeun')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='actress',
            field=models.CharField(choices=[('Viola Davis', 'Viola Davis'), ('Andra Day', 'Andra Day'), ('Vanessa Kirby', 'Vanessa Kirby'), ('Frances McDormand', 'Frances McDormand'), ('Carey Mulligan', 'Carey Mulligan')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='animatedfeature',
            field=models.CharField(choices=[('Onward', 'Onward'), ('Over the Moon', 'Over the Moon'), ('A Shaun the Sheep Movie: Farmageddon', 'A Shaun the Sheep Movie: Farmageddon'), ('Soul', 'Soul'), ('Wolfwalkers', 'Wolfwalkers')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='animatedshort',
            field=models.CharField(choices=[('Burrow', 'Burrow'), ('Genius Loci', 'Genius Loci'), ('If Anything Happens I Love You', 'If Anything Happens I Love You'), ('Opera', 'Opera'), ('Yes-People', 'Yes-People')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='bestpicture',
            field=models.CharField(choices=[('The Father', 'The Father'), ('Judas and the Black Messiah', 'Judas and the Black Messiah'), ('Mank', 'Mank'), ('Minari', 'Minari'), ('Nomadland', 'Nomadland'), ('Promising Young Woman', 'Promising Young Woman'), ('Sound of Metal', 'Sound of Metal'), ('The Trial of the Chicago 7', 'The Trial of the Chicago 7')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='cinematography',
            field=models.CharField(choices=[('Judas and the Black Messiah', 'Judas and the Black Messiah'), ('Mank', 'Mank'), ('News of the World', 'News of the World'), ('Nomadland', 'Nomadland'), ('The Trial of the Chicago 7', 'The Trial of the Chicago 7')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='costume',
            field=models.CharField(choices=[('Emma', 'Emma'), ("Ma Rainey's Black Bottom", "Ma Rainey's Black Bottom"), ('Mank', 'Mank'), ('Mulan', 'Mulan'), ('Pinocchio', 'Pinocchio')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='directing',
            field=models.CharField(choices=[('Another Round', 'Another Round'), ('Mank', 'Mank'), ('Minari', 'Minari'), ('Nomadland', 'Nomadland'), ('Promising Young Woman', 'Promising Young Woman')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='docshort',
            field=models.CharField(choices=[('Colette', 'Colette'), ('A Concerto is a Conversation', 'A Concerto is a Conversation'), ('Do Not Split', 'Do Not Split'), ('Hunger Ward', 'Hunger Ward'), ('A Love Song For Latasha', 'A Love Song For Latasha')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='documentary',
            field=models.CharField(choices=[('Collective', 'Collective'), ('Crip Camp', 'Crip Camp'), ('The Mole Agent', 'The Mole Agent'), ('My Octopus Teacher', 'My Octopus Teacher'), ('Time', 'Time')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='fediting',
            field=models.CharField(choices=[('The Father', 'The Father'), ('Nomadland', 'Nomadland'), ('Promising Young Woman', 'Promising Young Woman'), ('Sound of Metal', 'Sound of Metal'), ('The Trial of the Chicago 7', 'The Trial of the Chicago 7')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='foreign',
            field=models.CharField(choices=[('Another Round', 'Another Round'), ('Better Days', 'Better Days'), ('Collective', 'Collective'), ('The Man Who Sold His Skin', 'The Man Who Sold His Skin'), ('Quo Vadis, Aida?', 'Quo Vadis, Aida?')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='makeupandh',
            field=models.CharField(choices=[('Emma', 'Emma'), ('Hillbilly Elegy', 'Hillbilly Elegy'), ("Ma Rainey's Black Bottom", "Ma Rainey's Black Bottom"), ('Mank', 'Mank'), ('Pinocchio', 'Pinocchio')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='mscore',
            field=models.CharField(choices=[('Da 5 Bloods', 'Da 5 Bloods'), ('Mank', 'Mank'), ('Minari', 'Minari'), ('News of the World', 'News of the World'), ('Soul', 'Soul')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='msong',
            field=models.CharField(choices=[('Fight For You', 'Fight For You'), ('Hear My Voice', 'Hear My Voice'), ('Husavik', 'Husavik'), ('Io Si (Seen)', 'Io Si (Seen)'), ('Speak Now', 'Speak Now')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='prodesign',
            field=models.CharField(choices=[('The Father', 'The Father'), ("Ma Rainey's Black Bottom", "Ma Rainey's Black Bottom"), ('Mank', 'Mank'), ('News of the World', 'News of the World'), ('Tenet', 'Tenet')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='sediting',
            field=models.CharField(choices=[('Greyhound', 'Greyhound'), ('Mank', 'Mank'), ('News of the World', 'News of the World'), ('Sound of Metal', 'Sound of Metal'), ('Soul', 'Soul')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='shortfilm',
            field=models.CharField(choices=[('Feeling Through', 'Feeling Through'), ('The Letter Room', 'The Letter Room'), ('The Present', 'The Present'), ('Two Distant Strangers', 'Two Distant Strangers'), ('White Eye', 'White Eye')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='smixing',
            field=models.CharField(choices=[('Greyhound', 'Greyhound'), ('Mank', 'Mank'), ('News of the World', 'News of the World'), ('Sound of Metal', 'Sound of Metal'), ('Soul', 'Soul')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='supactor',
            field=models.CharField(choices=[('Sacha Baron Cohen', 'Sacha Baron Cohen'), ('Daniel Kaluuya', 'Daniel Kaluuya'), ('Leslie Odom Jr.', 'Leslie Odom Jr.'), ('Paul Raci', 'Paul Raci'), ('Lakeith Stanfield', 'Lakeith Stanfield')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='supactress',
            field=models.CharField(choices=[('Maria Bakalova', 'Maria Bakalova'), ('Glenn Close', 'Glenn Close'), ('Olivia Colman', 'Olivia Colman'), ('Amanda Seyfried', 'Amanda Seyfried'), ('Youn Yuh-jung', 'Youn Yuh-jung')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='visualfx',
            field=models.CharField(choices=[('Love and Monsters', 'Love and Monsters'), ('The Midnight Sky', 'The Midnight Sky'), ('Mulan', 'Mulan'), ('The One and Only Ivan', 'The One and Only Ivan'), ('Tenet', 'Tenet')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='writingad',
            field=models.CharField(choices=[('Borat Subsequent Moviefilm', 'Borat Subsequent Moviefilm'), ('The Father', 'The Father'), ('Nomadland', 'Nomadland'), ('One Night in Miami...', 'One Night in Miami...'), ('The White Tiger', 'The White Tiger')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='writingor',
            field=models.CharField(choices=[('Judas and the Black Messiah', 'Judas and the Black Messiah'), ('Minari', 'Minari'), ('Promising Young Woman', 'Promising Young Woman'), ('Sound of Metal', 'Sound of Metal'), ('The Trial of the Chicago 7', 'The Trial of the Chicago 7')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='actor',
            field=models.CharField(choices=[('Riz Ahmed', 'Riz Ahmed'), ('Chadwick Boseman', 'Chadwick Boseman'), ('Anthony Hopkins', 'Anthony Hopkins'), ('Gary Oldman', 'Gary Oldman'), ('Steven Yeun', 'Steven Yeun')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='actress',
            field=models.CharField(choices=[('Viola Davis', 'Viola Davis'), ('Andra Day', 'Andra Day'), ('Vanessa Kirby', 'Vanessa Kirby'), ('Frances McDormand', 'Frances McDormand'), ('Carey Mulligan', 'Carey Mulligan')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='animatedfeature',
            field=models.CharField(choices=[('Onward', 'Onward'), ('Over the Moon', 'Over the Moon'), ('A Shaun the Sheep Movie: Farmageddon', 'A Shaun the Sheep Movie: Farmageddon'), ('Soul', 'Soul'), ('Wolfwalkers', 'Wolfwalkers')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='animatedshort',
            field=models.CharField(choices=[('Burrow', 'Burrow'), ('Genius Loci', 'Genius Loci'), ('If Anything Happens I Love You', 'If Anything Happens I Love You'), ('Opera', 'Opera'), ('Yes-People', 'Yes-People')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='bestpicture',
            field=models.CharField(choices=[('The Father', 'The Father'), ('Judas and the Black Messiah', 'Judas and the Black Messiah'), ('Mank', 'Mank'), ('Minari', 'Minari'), ('Nomadland', 'Nomadland'), ('Promising Young Woman', 'Promising Young Woman'), ('Sound of Metal', 'Sound of Metal'), ('The Trial of the Chicago 7', 'The Trial of the Chicago 7')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='cinematography',
            field=models.CharField(choices=[('Judas and the Black Messiah', 'Judas and the Black Messiah'), ('Mank', 'Mank'), ('News of the World', 'News of the World'), ('Nomadland', 'Nomadland'), ('The Trial of the Chicago 7', 'The Trial of the Chicago 7')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='costume',
            field=models.CharField(choices=[('Emma', 'Emma'), ("Ma Rainey's Black Bottom", "Ma Rainey's Black Bottom"), ('Mank', 'Mank'), ('Mulan', 'Mulan'), ('Pinocchio', 'Pinocchio')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='directing',
            field=models.CharField(choices=[('Another Round', 'Another Round'), ('Mank', 'Mank'), ('Minari', 'Minari'), ('Nomadland', 'Nomadland'), ('Promising Young Woman', 'Promising Young Woman')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='docshort',
            field=models.CharField(choices=[('Colette', 'Colette'), ('A Concerto is a Conversation', 'A Concerto is a Conversation'), ('Do Not Split', 'Do Not Split'), ('Hunger Ward', 'Hunger Ward'), ('A Love Song For Latasha', 'A Love Song For Latasha')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='documentary',
            field=models.CharField(choices=[('Collective', 'Collective'), ('Crip Camp', 'Crip Camp'), ('The Mole Agent', 'The Mole Agent'), ('My Octopus Teacher', 'My Octopus Teacher'), ('Time', 'Time')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='fediting',
            field=models.CharField(choices=[('The Father', 'The Father'), ('Nomadland', 'Nomadland'), ('Promising Young Woman', 'Promising Young Woman'), ('Sound of Metal', 'Sound of Metal'), ('The Trial of the Chicago 7', 'The Trial of the Chicago 7')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='foreign',
            field=models.CharField(choices=[('Another Round', 'Another Round'), ('Better Days', 'Better Days'), ('Collective', 'Collective'), ('The Man Who Sold His Skin', 'The Man Who Sold His Skin'), ('Quo Vadis, Aida?', 'Quo Vadis, Aida?')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='makeupandh',
            field=models.CharField(choices=[('Emma', 'Emma'), ('Hillbilly Elegy', 'Hillbilly Elegy'), ("Ma Rainey's Black Bottom", "Ma Rainey's Black Bottom"), ('Mank', 'Mank'), ('Pinocchio', 'Pinocchio')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='mscore',
            field=models.CharField(choices=[('Da 5 Bloods', 'Da 5 Bloods'), ('Mank', 'Mank'), ('Minari', 'Minari'), ('News of the World', 'News of the World'), ('Soul', 'Soul')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='msong',
            field=models.CharField(choices=[('Fight For You', 'Fight For You'), ('Hear My Voice', 'Hear My Voice'), ('Husavik', 'Husavik'), ('Io Si (Seen)', 'Io Si (Seen)'), ('Speak Now', 'Speak Now')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='prodesign',
            field=models.CharField(choices=[('The Father', 'The Father'), ("Ma Rainey's Black Bottom", "Ma Rainey's Black Bottom"), ('Mank', 'Mank'), ('News of the World', 'News of the World'), ('Tenet', 'Tenet')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='sediting',
            field=models.CharField(choices=[('Greyhound', 'Greyhound'), ('Mank', 'Mank'), ('News of the World', 'News of the World'), ('Sound of Metal', 'Sound of Metal'), ('Soul', 'Soul')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='shortfilm',
            field=models.CharField(choices=[('Feeling Through', 'Feeling Through'), ('The Letter Room', 'The Letter Room'), ('The Present', 'The Present'), ('Two Distant Strangers', 'Two Distant Strangers'), ('White Eye', 'White Eye')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='smixing',
            field=models.CharField(choices=[('Greyhound', 'Greyhound'), ('Mank', 'Mank'), ('News of the World', 'News of the World'), ('Sound of Metal', 'Sound of Metal'), ('Soul', 'Soul')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='supactor',
            field=models.CharField(choices=[('Sacha Baron Cohen', 'Sacha Baron Cohen'), ('Daniel Kaluuya', 'Daniel Kaluuya'), ('Leslie Odom Jr.', 'Leslie Odom Jr.'), ('Paul Raci', 'Paul Raci'), ('Lakeith Stanfield', 'Lakeith Stanfield')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='supactress',
            field=models.CharField(choices=[('Maria Bakalova', 'Maria Bakalova'), ('Glenn Close', 'Glenn Close'), ('Olivia Colman', 'Olivia Colman'), ('Amanda Seyfried', 'Amanda Seyfried'), ('Youn Yuh-jung', 'Youn Yuh-jung')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='visualfx',
            field=models.CharField(choices=[('Love and Monsters', 'Love and Monsters'), ('The Midnight Sky', 'The Midnight Sky'), ('Mulan', 'Mulan'), ('The One and Only Ivan', 'The One and Only Ivan'), ('Tenet', 'Tenet')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='writingad',
            field=models.CharField(choices=[('Borat Subsequent Moviefilm', 'Borat Subsequent Moviefilm'), ('The Father', 'The Father'), ('Nomadland', 'Nomadland'), ('One Night in Miami...', 'One Night in Miami...'), ('The White Tiger', 'The White Tiger')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='writingor',
            field=models.CharField(choices=[('Judas and the Black Messiah', 'Judas and the Black Messiah'), ('Minari', 'Minari'), ('Promising Young Woman', 'Promising Young Woman'), ('Sound of Metal', 'Sound of Metal'), ('The Trial of the Chicago 7', 'The Trial of the Chicago 7')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='actor',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Riz Ahmed', 'Riz Ahmed'), ('Chadwick Boseman', 'Chadwick Boseman'), ('Anthony Hopkins', 'Anthony Hopkins'), ('Gary Oldman', 'Gary Oldman'), ('Steven Yeun', 'Steven Yeun')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='actress',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Viola Davis', 'Viola Davis'), ('Andra Day', 'Andra Day'), ('Vanessa Kirby', 'Vanessa Kirby'), ('Frances McDormand', 'Frances McDormand'), ('Carey Mulligan', 'Carey Mulligan')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='animatedfeature',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Onward', 'Onward'), ('Over the Moon', 'Over the Moon'), ('A Shaun the Sheep Movie: Farmageddon', 'A Shaun the Sheep Movie: Farmageddon'), ('Soul', 'Soul'), ('Wolfwalkers', 'Wolfwalkers')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='animatedshort',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Burrow', 'Burrow'), ('Genius Loci', 'Genius Loci'), ('If Anything Happens I Love You', 'If Anything Happens I Love You'), ('Opera', 'Opera'), ('Yes-People', 'Yes-People')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='bestpicture',
            field=models.CharField(choices=[('tbd', 'tbd'), ('The Father', 'The Father'), ('Judas and the Black Messiah', 'Judas and the Black Messiah'), ('Mank', 'Mank'), ('Minari', 'Minari'), ('Nomadland', 'Nomadland'), ('Promising Young Woman', 'Promising Young Woman'), ('Sound of Metal', 'Sound of Metal'), ('The Trial of the Chicago 7', 'The Trial of the Chicago 7')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='cinematography',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Judas and the Black Messiah', 'Judas and the Black Messiah'), ('Mank', 'Mank'), ('News of the World', 'News of the World'), ('Nomadland', 'Nomadland'), ('The Trial of the Chicago 7', 'The Trial of the Chicago 7')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='costume',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Emma', 'Emma'), ("Ma Rainey's Black Bottom", "Ma Rainey's Black Bottom"), ('Mank', 'Mank'), ('Mulan', 'Mulan'), ('Pinocchio', 'Pinocchio')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='directing',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Another Round', 'Another Round'), ('Mank', 'Mank'), ('Minari', 'Minari'), ('Nomadland', 'Nomadland'), ('Promising Young Woman', 'Promising Young Woman')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='docshort',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Colette', 'Colette'), ('A Concerto is a Conversation', 'A Concerto is a Conversation'), ('Do Not Split', 'Do Not Split'), ('Hunger Ward', 'Hunger Ward'), ('A Love Song For Latasha', 'A Love Song For Latasha')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='documentary',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Collective', 'Collective'), ('Crip Camp', 'Crip Camp'), ('The Mole Agent', 'The Mole Agent'), ('My Octopus Teacher', 'My Octopus Teacher'), ('Time', 'Time')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='fediting',
            field=models.CharField(choices=[('tbd', 'tbd'), ('The Father', 'The Father'), ('Nomadland', 'Nomadland'), ('Promising Young Woman', 'Promising Young Woman'), ('Sound of Metal', 'Sound of Metal'), ('The Trial of the Chicago 7', 'The Trial of the Chicago 7')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='foreign',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Another Round', 'Another Round'), ('Better Days', 'Better Days'), ('Collective', 'Collective'), ('The Man Who Sold His Skin', 'The Man Who Sold His Skin'), ('Quo Vadis, Aida?', 'Quo Vadis, Aida?')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='makeupandh',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Emma', 'Emma'), ('Hillbilly Elegy', 'Hillbilly Elegy'), ("Ma Rainey's Black Bottom", "Ma Rainey's Black Bottom"), ('Mank', 'Mank'), ('Pinocchio', 'Pinocchio')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='mscore',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Da 5 Bloods', 'Da 5 Bloods'), ('Mank', 'Mank'), ('Minari', 'Minari'), ('News of the World', 'News of the World'), ('Soul', 'Soul')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='msong',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Fight For You', 'Fight For You'), ('Hear My Voice', 'Hear My Voice'), ('Husavik', 'Husavik'), ('Io Si (Seen)', 'Io Si (Seen)'), ('Speak Now', 'Speak Now')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='prodesign',
            field=models.CharField(choices=[('tbd', 'tbd'), ('The Father', 'The Father'), ("Ma Rainey's Black Bottom", "Ma Rainey's Black Bottom"), ('Mank', 'Mank'), ('News of the World', 'News of the World'), ('Tenet', 'Tenet')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='sediting',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Greyhound', 'Greyhound'), ('Mank', 'Mank'), ('News of the World', 'News of the World'), ('Sound of Metal', 'Sound of Metal'), ('Soul', 'Soul')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='shortfilm',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Feeling Through', 'Feeling Through'), ('The Letter Room', 'The Letter Room'), ('The Present', 'The Present'), ('Two Distant Strangers', 'Two Distant Strangers'), ('White Eye', 'White Eye')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='smixing',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Greyhound', 'Greyhound'), ('Mank', 'Mank'), ('News of the World', 'News of the World'), ('Sound of Metal', 'Sound of Metal'), ('Soul', 'Soul')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='supactor',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Sacha Baron Cohen', 'Sacha Baron Cohen'), ('Daniel Kaluuya', 'Daniel Kaluuya'), ('Leslie Odom Jr.', 'Leslie Odom Jr.'), ('Paul Raci', 'Paul Raci'), ('Lakeith Stanfield', 'Lakeith Stanfield')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='supactress',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Maria Bakalova', 'Maria Bakalova'), ('Glenn Close', 'Glenn Close'), ('Olivia Colman', 'Olivia Colman'), ('Amanda Seyfried', 'Amanda Seyfried'), ('Youn Yuh-jung', 'Youn Yuh-jung')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='visualfx',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Love and Monsters', 'Love and Monsters'), ('The Midnight Sky', 'The Midnight Sky'), ('Mulan', 'Mulan'), ('The One and Only Ivan', 'The One and Only Ivan'), ('Tenet', 'Tenet')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='writingad',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Borat Subsequent Moviefilm', 'Borat Subsequent Moviefilm'), ('The Father', 'The Father'), ('Nomadland', 'Nomadland'), ('One Night in Miami...', 'One Night in Miami...'), ('The White Tiger', 'The White Tiger')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='writingor',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Judas and the Black Messiah', 'Judas and the Black Messiah'), ('Minari', 'Minari'), ('Promising Young Woman', 'Promising Young Woman'), ('Sound of Metal', 'Sound of Metal'), ('The Trial of the Chicago 7', 'The Trial of the Chicago 7')], default='NA', max_length=100),
        ),
    ]
