# Generated by Django 2.1.4 on 2021-04-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscarsapp', '0006_auto_20210402_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oscarballot',
            old_name='sediting',
            new_name='sound',
        ),
        migrations.RenameField(
            model_name='umslballot',
            old_name='sediting',
            new_name='sound',
        ),
        migrations.RenameField(
            model_name='winners',
            old_name='sediting',
            new_name='sound',
        ),
    ]
