# Generated by Django 2.1.4 on 2021-04-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscarsapp', '0007_auto_20210407_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oscarballot',
            name='smixing',
        ),
        migrations.RemoveField(
            model_name='umslballot',
            name='smixing',
        ),
        migrations.RemoveField(
            model_name='winners',
            name='smixing',
        ),
    ]
