# Generated by Django 2.0.2 on 2022-03-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscarsapp', '0008_auto_20210407_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oscarballot',
            name='actor',
            field=models.CharField(choices=[('Javier Bardem', 'Javier Bardem'), ('Benedict Cumberbatch', 'Benedict Cumberbatch'), ('Andrew Garfield', 'Andrew Garfield'), ('Will Smith', 'Will Smith'), ('Denzel Washington', 'Denzel Washington')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='actress',
            field=models.CharField(choices=[('Jessica Chastain', 'Jessica Chastain'), ('Olivia Colman', 'Olivia Colman'), ('Penelope Cruz', 'Penelope Cruz'), ('Nicole Kidman', 'Nicole Kidman'), ('Kristen Stewart', 'Kristen Stewart')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='animatedfeature',
            field=models.CharField(choices=[('Encanto', 'Encanto'), ('Flee', 'Flee'), ('Luca', 'Luca'), ('The Mitchells vs. the Machines', 'The Mitchells vs. the Machines'), ('Raya and the Last Dragon', 'Raya and the Last Dragon')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='animatedshort',
            field=models.CharField(choices=[('Affairs of the Art', 'Affairs of the Art'), ('Bestia', 'Bestia'), ('Boxballet', 'Boxballet'), ('Robin Robin', 'Robin Robin'), ('The Windshield Wiper', 'The Windshield Wiper')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='bestpicture',
            field=models.CharField(choices=[('Belfast', 'Belfast'), ('CODA', 'CODA'), ("Don't Look Up", "Don't Look Up"), ('Drive My Car', 'Drive My Car'), ('Dune', 'Dune'), ('King Richard', 'King Richard'), ('Licorice Pizza', 'Licorice Pizza'), ('Nightmare Alley', 'Nightmare Alley'), ('The Power of the Dog', 'The Power of the Dog'), ('West Side Story', 'West Side Story')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='cinematography',
            field=models.CharField(choices=[('Dune', 'Dune'), ('Nightmare Alley', 'Nightmare Alley'), ('The Power of the Dog', 'The Power of the Dog'), ('The Tragedy of Macbeth', 'The Tragedy of Macbeth'), ('West Side Story', 'West Side Story')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='costume',
            field=models.CharField(choices=[('Cruella', 'Cruella'), ('Cyrano', 'Cyrano'), ('Dune', 'Dune'), ('Nightmare Alley', 'Nightmare Alley'), ('West Side Story', 'West Side Story')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='directing',
            field=models.CharField(choices=[('Belfast', 'Belfast'), ('Drive My Car', 'Drive My Car'), ('Licorice Pizza', 'Licorice Pizza'), ('The Power of the Dog', 'The Power of the Dog'), ('West Side Story', 'West Side Story')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='docshort',
            field=models.CharField(choices=[('Audible', 'Audible'), ('Lead Me Home', 'Lead Me Home'), ('The Queen of Basketball', 'The Queen of Basketball'), ('Three Songs for Benazir', 'Three Songs for Benazir'), ('When We Were Bullies', 'When We Were Bullies')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='documentary',
            field=models.CharField(choices=[('Ascension', 'Ascension'), ('Attica', 'Attica'), ('Flee', 'Flee'), ('Summer of Soul (...or when the Revolution could not be Televised)', 'Summer of Soul (...or when the Revolution could not be Televised)'), ('Writing with Fire', 'Writing with Fire')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='fediting',
            field=models.CharField(choices=[("Don't Look Up", "Don't Look Up"), ('Dune', 'Dune'), ('King Richard', 'King Richard'), ('The Power of the Dog', 'The Power of the Dog'), ('Tick, Tick... Boom', 'Tick, Tick... Boom')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='foreign',
            field=models.CharField(choices=[('Drive My Car', 'Drive My Car'), ('Flee', 'Flee'), ('The Hand of God', 'The Hand of God'), ('Lunana: A Yak in the Classroom', 'Lunana: A Yak in the Classroom'), ('The Worst Person in the World', 'The Worst Person in the World')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='makeupandh',
            field=models.CharField(choices=[('Coming 2 America', 'Coming 2 America'), ('Cruella', 'Cruella'), ('Dune', 'Dune'), ('The Eyes of Tammy Faye', 'The Eyes of Tammy Faye'), ('House of Gucci', 'House of Gucci')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='mscore',
            field=models.CharField(choices=[("Don't Look Up", "Don't Look Up"), ('Dune', 'Dune'), ('Encanto', 'Encanto'), ('Parallel Mothers', 'Parallel Mothers'), ('The Power of the Dog', 'The Power of the Dog')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='msong',
            field=models.CharField(choices=[('Be Alive', 'Be Alive'), ('Dos Oruguitas', 'Dos Oruguitas'), ('Down To Joy', 'Down To Joy'), ('No Time To Die', 'No Time To Die'), ('Somehow You Do', 'Somehow You Do')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='prodesign',
            field=models.CharField(choices=[('Dune', 'Dune'), ('Nightmare Alley', 'Nightmare Alley'), ('The Power of the Dog', 'The Power of the Dog'), ('The Tragedy of Macbeth', 'The Tragedy of Macbeth'), ('West Side Story', 'West Side Story')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='shortfilm',
            field=models.CharField(choices=[('Ala Kachuu - Take and Run', 'Ala Kachuu - Take and Run'), ('The Dress', 'The Dress'), ('The Long Goodbye', 'The Long Goodbye'), ('On My Mind', 'On My Mind'), ('Please Hold', 'Please Hold')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='sound',
            field=models.CharField(choices=[('Belfast', 'Belfast'), ('Dune', 'Dune'), ('No Time to Die', 'No Time to Die'), ('The Power of the Dog', 'The Power of the Dog'), ('West Side Story', 'West Side Story')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='supactor',
            field=models.CharField(choices=[('Ciaran Hinds', 'Ciaran Hinds'), ('Troy Kotsur', 'Troy Kotsur'), ('Jesse Plemons', 'Jesse Plemons'), ('J.K. Simmons', 'J.K. Simmons'), ('Kodi Smit-McPhee', 'Kodi Smit-McPhee')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='supactress',
            field=models.CharField(choices=[('Jessie Buckley', 'Jessie Buckley'), ('Ariana DeBose', 'Ariana DeBose'), ('Judi Dench', 'Judi Dench'), ('Kirsten Dunst', 'Kirsten Dunst'), ('Aunjanue Ellis', 'Aunjanue Ellis')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='visualfx',
            field=models.CharField(choices=[('Dune', 'Dune'), ('Free Guy', 'Free Guy'), ('No Time to Die', 'No Time to Die'), ('Shang-Chi and the Legend of the Ten Rings', 'Shang-Chi and the Legend of the Ten Rings'), ('Spider-Man: No Way Home', 'Spider-Man: No Way Home')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='writingad',
            field=models.CharField(choices=[('CODA', 'CODA'), ('Drive My Car', 'Drive My Car'), ('Dune', 'Dune'), ('The Lost Daughter', 'The Lost Daughter'), ('The Power of the Dog', 'The Power of the Dog')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='writingor',
            field=models.CharField(choices=[('Belfast', 'Belfast'), ("Don't Look Up", "Don't Look Up"), ('King Richard', 'King Richard'), ('Licorice Pizza', 'Licorice Pizza'), ('The Worst Person in the World', 'The Worst Person in the World')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='actor',
            field=models.CharField(choices=[('Javier Bardem', 'Javier Bardem'), ('Benedict Cumberbatch', 'Benedict Cumberbatch'), ('Andrew Garfield', 'Andrew Garfield'), ('Will Smith', 'Will Smith'), ('Denzel Washington', 'Denzel Washington')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='actress',
            field=models.CharField(choices=[('Jessica Chastain', 'Jessica Chastain'), ('Olivia Colman', 'Olivia Colman'), ('Penelope Cruz', 'Penelope Cruz'), ('Nicole Kidman', 'Nicole Kidman'), ('Kristen Stewart', 'Kristen Stewart')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='animatedfeature',
            field=models.CharField(choices=[('Encanto', 'Encanto'), ('Flee', 'Flee'), ('Luca', 'Luca'), ('The Mitchells vs. the Machines', 'The Mitchells vs. the Machines'), ('Raya and the Last Dragon', 'Raya and the Last Dragon')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='animatedshort',
            field=models.CharField(choices=[('Affairs of the Art', 'Affairs of the Art'), ('Bestia', 'Bestia'), ('Boxballet', 'Boxballet'), ('Robin Robin', 'Robin Robin'), ('The Windshield Wiper', 'The Windshield Wiper')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='bestpicture',
            field=models.CharField(choices=[('Belfast', 'Belfast'), ('CODA', 'CODA'), ("Don't Look Up", "Don't Look Up"), ('Drive My Car', 'Drive My Car'), ('Dune', 'Dune'), ('King Richard', 'King Richard'), ('Licorice Pizza', 'Licorice Pizza'), ('Nightmare Alley', 'Nightmare Alley'), ('The Power of the Dog', 'The Power of the Dog'), ('West Side Story', 'West Side Story')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='cinematography',
            field=models.CharField(choices=[('Dune', 'Dune'), ('Nightmare Alley', 'Nightmare Alley'), ('The Power of the Dog', 'The Power of the Dog'), ('The Tragedy of Macbeth', 'The Tragedy of Macbeth'), ('West Side Story', 'West Side Story')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='costume',
            field=models.CharField(choices=[('Cruella', 'Cruella'), ('Cyrano', 'Cyrano'), ('Dune', 'Dune'), ('Nightmare Alley', 'Nightmare Alley'), ('West Side Story', 'West Side Story')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='directing',
            field=models.CharField(choices=[('Belfast', 'Belfast'), ('Drive My Car', 'Drive My Car'), ('Licorice Pizza', 'Licorice Pizza'), ('The Power of the Dog', 'The Power of the Dog'), ('West Side Story', 'West Side Story')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='docshort',
            field=models.CharField(choices=[('Audible', 'Audible'), ('Lead Me Home', 'Lead Me Home'), ('The Queen of Basketball', 'The Queen of Basketball'), ('Three Songs for Benazir', 'Three Songs for Benazir'), ('When We Were Bullies', 'When We Were Bullies')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='documentary',
            field=models.CharField(choices=[('Ascension', 'Ascension'), ('Attica', 'Attica'), ('Flee', 'Flee'), ('Summer of Soul (...or when the Revolution could not be Televised)', 'Summer of Soul (...or when the Revolution could not be Televised)'), ('Writing with Fire', 'Writing with Fire')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='fediting',
            field=models.CharField(choices=[("Don't Look Up", "Don't Look Up"), ('Dune', 'Dune'), ('King Richard', 'King Richard'), ('The Power of the Dog', 'The Power of the Dog'), ('Tick, Tick... Boom', 'Tick, Tick... Boom')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='foreign',
            field=models.CharField(choices=[('Drive My Car', 'Drive My Car'), ('Flee', 'Flee'), ('The Hand of God', 'The Hand of God'), ('Lunana: A Yak in the Classroom', 'Lunana: A Yak in the Classroom'), ('The Worst Person in the World', 'The Worst Person in the World')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='makeupandh',
            field=models.CharField(choices=[('Coming 2 America', 'Coming 2 America'), ('Cruella', 'Cruella'), ('Dune', 'Dune'), ('The Eyes of Tammy Faye', 'The Eyes of Tammy Faye'), ('House of Gucci', 'House of Gucci')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='mscore',
            field=models.CharField(choices=[("Don't Look Up", "Don't Look Up"), ('Dune', 'Dune'), ('Encanto', 'Encanto'), ('Parallel Mothers', 'Parallel Mothers'), ('The Power of the Dog', 'The Power of the Dog')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='msong',
            field=models.CharField(choices=[('Be Alive', 'Be Alive'), ('Dos Oruguitas', 'Dos Oruguitas'), ('Down To Joy', 'Down To Joy'), ('No Time To Die', 'No Time To Die'), ('Somehow You Do', 'Somehow You Do')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='prodesign',
            field=models.CharField(choices=[('Dune', 'Dune'), ('Nightmare Alley', 'Nightmare Alley'), ('The Power of the Dog', 'The Power of the Dog'), ('The Tragedy of Macbeth', 'The Tragedy of Macbeth'), ('West Side Story', 'West Side Story')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='shortfilm',
            field=models.CharField(choices=[('Ala Kachuu - Take and Run', 'Ala Kachuu - Take and Run'), ('The Dress', 'The Dress'), ('The Long Goodbye', 'The Long Goodbye'), ('On My Mind', 'On My Mind'), ('Please Hold', 'Please Hold')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='sound',
            field=models.CharField(choices=[('Belfast', 'Belfast'), ('Dune', 'Dune'), ('No Time to Die', 'No Time to Die'), ('The Power of the Dog', 'The Power of the Dog'), ('West Side Story', 'West Side Story')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='supactor',
            field=models.CharField(choices=[('Ciaran Hinds', 'Ciaran Hinds'), ('Troy Kotsur', 'Troy Kotsur'), ('Jesse Plemons', 'Jesse Plemons'), ('J.K. Simmons', 'J.K. Simmons'), ('Kodi Smit-McPhee', 'Kodi Smit-McPhee')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='supactress',
            field=models.CharField(choices=[('Jessie Buckley', 'Jessie Buckley'), ('Ariana DeBose', 'Ariana DeBose'), ('Judi Dench', 'Judi Dench'), ('Kirsten Dunst', 'Kirsten Dunst'), ('Aunjanue Ellis', 'Aunjanue Ellis')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='visualfx',
            field=models.CharField(choices=[('Dune', 'Dune'), ('Free Guy', 'Free Guy'), ('No Time to Die', 'No Time to Die'), ('Shang-Chi and the Legend of the Ten Rings', 'Shang-Chi and the Legend of the Ten Rings'), ('Spider-Man: No Way Home', 'Spider-Man: No Way Home')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='writingad',
            field=models.CharField(choices=[('CODA', 'CODA'), ('Drive My Car', 'Drive My Car'), ('Dune', 'Dune'), ('The Lost Daughter', 'The Lost Daughter'), ('The Power of the Dog', 'The Power of the Dog')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='umslballot',
            name='writingor',
            field=models.CharField(choices=[('Belfast', 'Belfast'), ("Don't Look Up", "Don't Look Up"), ('King Richard', 'King Richard'), ('Licorice Pizza', 'Licorice Pizza'), ('The Worst Person in the World', 'The Worst Person in the World')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='actor',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Javier Bardem', 'Javier Bardem'), ('Benedict Cumberbatch', 'Benedict Cumberbatch'), ('Andrew Garfield', 'Andrew Garfield'), ('Will Smith', 'Will Smith'), ('Denzel Washington', 'Denzel Washington')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='actress',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Jessica Chastain', 'Jessica Chastain'), ('Olivia Colman', 'Olivia Colman'), ('Penelope Cruz', 'Penelope Cruz'), ('Nicole Kidman', 'Nicole Kidman'), ('Kristen Stewart', 'Kristen Stewart')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='animatedfeature',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Encanto', 'Encanto'), ('Flee', 'Flee'), ('Luca', 'Luca'), ('The Mitchells vs. the Machines', 'The Mitchells vs. the Machines'), ('Raya and the Last Dragon', 'Raya and the Last Dragon')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='animatedshort',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Affairs of the Art', 'Affairs of the Art'), ('Bestia', 'Bestia'), ('Boxballet', 'Boxballet'), ('Robin Robin', 'Robin Robin'), ('The Windshield Wiper', 'The Windshield Wiper')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='bestpicture',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Belfast', 'Belfast'), ('CODA', 'CODA'), ("Don't Look Up", "Don't Look Up"), ('Drive My Car', 'Drive My Car'), ('Dune', 'Dune'), ('King Richard', 'King Richard'), ('Licorice Pizza', 'Licorice Pizza'), ('Nightmare Alley', 'Nightmare Alley'), ('The Power of the Dog', 'The Power of the Dog'), ('West Side Story', 'West Side Story')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='cinematography',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Dune', 'Dune'), ('Nightmare Alley', 'Nightmare Alley'), ('The Power of the Dog', 'The Power of the Dog'), ('The Tragedy of Macbeth', 'The Tragedy of Macbeth'), ('West Side Story', 'West Side Story')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='costume',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Cruella', 'Cruella'), ('Cyrano', 'Cyrano'), ('Dune', 'Dune'), ('Nightmare Alley', 'Nightmare Alley'), ('West Side Story', 'West Side Story')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='directing',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Belfast', 'Belfast'), ('Drive My Car', 'Drive My Car'), ('Licorice Pizza', 'Licorice Pizza'), ('The Power of the Dog', 'The Power of the Dog'), ('West Side Story', 'West Side Story')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='docshort',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Audible', 'Audible'), ('Lead Me Home', 'Lead Me Home'), ('The Queen of Basketball', 'The Queen of Basketball'), ('Three Songs for Benazir', 'Three Songs for Benazir'), ('When We Were Bullies', 'When We Were Bullies')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='documentary',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Ascension', 'Ascension'), ('Attica', 'Attica'), ('Flee', 'Flee'), ('Summer of Soul (...or when the Revolution could not be Televised)', 'Summer of Soul (...or when the Revolution could not be Televised)'), ('Writing with Fire', 'Writing with Fire')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='fediting',
            field=models.CharField(choices=[('tbd', 'tbd'), ("Don't Look Up", "Don't Look Up"), ('Dune', 'Dune'), ('King Richard', 'King Richard'), ('The Power of the Dog', 'The Power of the Dog'), ('Tick, Tick... Boom', 'Tick, Tick... Boom')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='foreign',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Drive My Car', 'Drive My Car'), ('Flee', 'Flee'), ('The Hand of God', 'The Hand of God'), ('Lunana: A Yak in the Classroom', 'Lunana: A Yak in the Classroom'), ('The Worst Person in the World', 'The Worst Person in the World')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='makeupandh',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Coming 2 America', 'Coming 2 America'), ('Cruella', 'Cruella'), ('Dune', 'Dune'), ('The Eyes of Tammy Faye', 'The Eyes of Tammy Faye'), ('House of Gucci', 'House of Gucci')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='mscore',
            field=models.CharField(choices=[('tbd', 'tbd'), ("Don't Look Up", "Don't Look Up"), ('Dune', 'Dune'), ('Encanto', 'Encanto'), ('Parallel Mothers', 'Parallel Mothers'), ('The Power of the Dog', 'The Power of the Dog')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='msong',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Be Alive', 'Be Alive'), ('Dos Oruguitas', 'Dos Oruguitas'), ('Down To Joy', 'Down To Joy'), ('No Time To Die', 'No Time To Die'), ('Somehow You Do', 'Somehow You Do')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='prodesign',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Dune', 'Dune'), ('Nightmare Alley', 'Nightmare Alley'), ('The Power of the Dog', 'The Power of the Dog'), ('The Tragedy of Macbeth', 'The Tragedy of Macbeth'), ('West Side Story', 'West Side Story')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='shortfilm',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Ala Kachuu - Take and Run', 'Ala Kachuu - Take and Run'), ('The Dress', 'The Dress'), ('The Long Goodbye', 'The Long Goodbye'), ('On My Mind', 'On My Mind'), ('Please Hold', 'Please Hold')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='sound',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Belfast', 'Belfast'), ('Dune', 'Dune'), ('No Time to Die', 'No Time to Die'), ('The Power of the Dog', 'The Power of the Dog'), ('West Side Story', 'West Side Story')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='supactor',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Ciaran Hinds', 'Ciaran Hinds'), ('Troy Kotsur', 'Troy Kotsur'), ('Jesse Plemons', 'Jesse Plemons'), ('J.K. Simmons', 'J.K. Simmons'), ('Kodi Smit-McPhee', 'Kodi Smit-McPhee')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='supactress',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Jessie Buckley', 'Jessie Buckley'), ('Ariana DeBose', 'Ariana DeBose'), ('Judi Dench', 'Judi Dench'), ('Kirsten Dunst', 'Kirsten Dunst'), ('Aunjanue Ellis', 'Aunjanue Ellis')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='visualfx',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Dune', 'Dune'), ('Free Guy', 'Free Guy'), ('No Time to Die', 'No Time to Die'), ('Shang-Chi and the Legend of the Ten Rings', 'Shang-Chi and the Legend of the Ten Rings'), ('Spider-Man: No Way Home', 'Spider-Man: No Way Home')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='writingad',
            field=models.CharField(choices=[('tbd', 'tbd'), ('CODA', 'CODA'), ('Drive My Car', 'Drive My Car'), ('Dune', 'Dune'), ('The Lost Daughter', 'The Lost Daughter'), ('The Power of the Dog', 'The Power of the Dog')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='writingor',
            field=models.CharField(choices=[('tbd', 'tbd'), ('Belfast', 'Belfast'), ("Don't Look Up", "Don't Look Up"), ('King Richard', 'King Richard'), ('Licorice Pizza', 'Licorice Pizza'), ('The Worst Person in the World', 'The Worst Person in the World')], default='NA', max_length=100),
        ),
    ]
