# Generated by Django 4.1.4 on 2023-03-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oscarsapp", "0009_auto_20220319_0530"),
    ]

    operations = [
        migrations.AddField(
            model_name="oscarballot",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="umslballot",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="actor",
            field=models.CharField(
                choices=[
                    ("Austin Butler", "Austin Butler"),
                    ("Bill Nighy", "Bill Nighy"),
                    ("Brendan Fraser", "Brendan Fraser"),
                    ("Colin Farrell", "Colin Farrell"),
                    ("Paul Mescal", "Paul Mescal"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="actress",
            field=models.CharField(
                choices=[
                    ("Ana de Armas", "Ana de Armas"),
                    ("Andrea Riseborough", "Andrea Riseborough"),
                    ("Cate Blanchett", "Cate Blanchett"),
                    ("Michelle Williams", "Michelle Williams"),
                    ("Michelle Yeoh", "Michelle Yeoh"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="animatedfeature",
            field=models.CharField(
                choices=[
                    (
                        "Guillermo del Toro's Pinocchio",
                        "Guillermo del Toro's Pinocchio",
                    ),
                    (
                        "Marcel the Shell with Shoes On",
                        "Marcel the Shell with Shoes On",
                    ),
                    ("Puss in Boots: The Last Wish", "Puss in Boots: The Last Wish"),
                    ("The Sea Beast", "The Sea Beast"),
                    ("Turning Red", "Turning Red"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="animatedshort",
            field=models.CharField(
                choices=[
                    (
                        "The Boy, the Mole, the Fox and the Horse",
                        "The Boy, the Mole, the Fox and the Horse",
                    ),
                    ("The Flying Sailor", "The Flying Sailor"),
                    ("Ice Merchants", "Ice Merchants"),
                    ("My Year of Dicks", "My Year of Dicks"),
                    (
                        "An Ostrich Told Me the World Is Fake and I Think I Believe It",
                        "An Ostrich Told Me the World Is Fake and I Think I Believe It",
                    ),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="bestpicture",
            field=models.CharField(
                choices=[
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("Avatar: The Way of Water", "Avatar: The Way of Water"),
                    ("Elvis", "Elvis"),
                    (
                        "Everything Everywhere All at Once",
                        "Everything Everywhere All at Once",
                    ),
                    ("The Banshees of Inisherin", "The Banshees of Inisherin"),
                    ("The Fabelmans", "The Fabelmans"),
                    ("Top Gun: Maverick", "Top Gun: Maverick"),
                    ("Triangle of Sadness", "Triangle of Sadness"),
                    ("Tar", "Tar"),
                    ("Women Talking", "Women Talking"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="cinematography",
            field=models.CharField(
                choices=[
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    (
                        "Bardo: False Chronicle of a Handful of Truths",
                        "Bardo: False Chronicle of a Handful of Truths",
                    ),
                    ("Elvis", "Elvis"),
                    ("Empire of Light", "Empire of Light"),
                    ("Tar", "Tar"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="costume",
            field=models.CharField(
                choices=[
                    ("Babylon", "Babylon"),
                    (
                        "Black Panther: Wakanda Forever",
                        "Black Panther: Wakanda Forever",
                    ),
                    ("Elvis", "Elvis"),
                    (
                        "Everything Everywhere All at Once",
                        "Everything Everywhere All at Once",
                    ),
                    ("Mrs. Harris Goes to Paris", "Mrs. Harris Goes to Paris"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="directing",
            field=models.CharField(
                choices=[
                    ("The Banshees of Inisherin", "The Banshees of Inisherin"),
                    (
                        "Everything Everywhere All at Once",
                        "Everything Everywhere All at Once",
                    ),
                    ("The Fabelmans", "The Fabelmans"),
                    ("Tar", "Tar"),
                    ("Triangle of Sadness", "Triangle of Sadness"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="docshort",
            field=models.CharField(
                choices=[
                    ("The Elephant Whisperers", "The Elephant Whisperers"),
                    ("Haulout", "Haulout"),
                    ("How Do You Measure a Year?", "How Do You Measure a Year?"),
                    ("The Martha Mitchell Effect", "The Martha Mitchell Effect"),
                    ("Stranger at the Gate", "Stranger at the Gate"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="documentary",
            field=models.CharField(
                choices=[
                    ("All That Breathes", "All That Breathes"),
                    (
                        "All the Beauty and the Bloodshed",
                        "All the Beauty and the Bloodshed",
                    ),
                    ("Fire of Love", "Fire of Love"),
                    ("A House Made of Splinters", "A House Made of Splinters"),
                    ("Navalny", "Navalny"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="fediting",
            field=models.CharField(
                choices=[
                    ("The Banshees of Inisherin", "The Banshees of Inisherin"),
                    ("Elvis", "Elvis"),
                    (
                        "Everything Everywhere All at Once",
                        "Everything Everywhere All at Once",
                    ),
                    ("Top Gun: Maverick", "Top Gun: Maverick"),
                    ("Tar", "Tar"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="foreign",
            field=models.CharField(
                choices=[
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("Argentina, 1985", "Argentina, 1985"),
                    ("Close", "Close"),
                    ("Eo", "Eo"),
                    ("The Quiet Girl", "The Quiet Girl"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="makeupandh",
            field=models.CharField(
                choices=[
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("The Batman", "The Batman"),
                    (
                        "Black Panther: Wakanda Forever",
                        "Black Panther: Wakanda Forever",
                    ),
                    ("Elvis", "Elvis"),
                    ("The Whale", "The Whale"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="mscore",
            field=models.CharField(
                choices=[
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("Babylon", "Babylon"),
                    ("The Banshees of Inisherin", "The Banshees of Inisherin"),
                    (
                        "Everything Everywhere All at Once",
                        "Everything Everywhere All at Once",
                    ),
                    ("The Fabelmans", "The Fabelmans"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="msong",
            field=models.CharField(
                choices=[
                    ("Applause", "Applause"),
                    ("Hold My Hand", "Hold My Hand"),
                    ("Lift Me Up", "Lift Me Up"),
                    ("Naatu Naatu", "Naatu Naatu"),
                    ("This Is a Life", "This Is a Life"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="prodesign",
            field=models.CharField(
                choices=[
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("Avatar: The Way of Water", "Avatar: The Way of Water"),
                    ("Babylon", "Babylon"),
                    ("Elvis", "Elvis"),
                    ("The Fabelmans", "The Fabelmans"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="shortfilm",
            field=models.CharField(
                choices=[
                    ("An Irish Goodbye", "An Irish Goodbye"),
                    ("Ivalu", "Ivalu"),
                    ("Le Pupille", "Le Pupille"),
                    ("Night Ride", "Night Ride"),
                    ("The Red Suitcase", "The Red Suitcase"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="sound",
            field=models.CharField(
                choices=[
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("Avatar: The Way of Water", "Avatar: The Way of Water"),
                    ("The Batman", "The Batman"),
                    ("Elvis", "Elvis"),
                    ("Top Gun: Maverick", "Top Gun: Maverick"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="supactor",
            field=models.CharField(
                choices=[
                    ("Barry Keoghan", "Barry Keoghan"),
                    ("Brendan Gleeson", "Brendan Gleeson"),
                    ("Brian Tyree Henry", "Brian Tyree Henry"),
                    ("Judd Hirsch", "Judd Hirsch"),
                    ("Ke Huy Quan", "Ke Huy Quan"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="supactress",
            field=models.CharField(
                choices=[
                    ("Angela Bassett", "Angela Bassett"),
                    ("Hong Chau", "Hong Chau"),
                    ("Jamie Lee Curtis", "Jamie Lee Curtis"),
                    ("Kerry Condon", "Kerry Condon"),
                    ("Stephanie Hsu", "Stephanie Hsu"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="visualfx",
            field=models.CharField(
                choices=[
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("Avatar: The Way of Water", "Avatar: The Way of Water"),
                    ("The Batman", "The Batman"),
                    (
                        "Black Panther: Wakanda Forever",
                        "Black Panther: Wakanda Forever",
                    ),
                    ("Top Gun: Maverick", "Top Gun: Maverick"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="writingad",
            field=models.CharField(
                choices=[
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("Glass Onion", "Glass Onion"),
                    ("Living", "Living"),
                    ("Top Gun: Maverick", "Top Gun: Maverick"),
                    ("Women Talking", "Women Talking"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="writingor",
            field=models.CharField(
                choices=[
                    (
                        "Everything Everywhere All at Once",
                        "Everything Everywhere All at Once",
                    ),
                    ("The Banshees of Inisherin", "The Banshees of Inisherin"),
                    ("The Fabelmans", "The Fabelmans"),
                    ("Triangle of Sadness", "Triangle of Sadness"),
                    ("Tar", "Tar"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="actor",
            field=models.CharField(
                choices=[
                    ("Austin Butler", "Austin Butler"),
                    ("Bill Nighy", "Bill Nighy"),
                    ("Brendan Fraser", "Brendan Fraser"),
                    ("Colin Farrell", "Colin Farrell"),
                    ("Paul Mescal", "Paul Mescal"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="actress",
            field=models.CharField(
                choices=[
                    ("Ana de Armas", "Ana de Armas"),
                    ("Andrea Riseborough", "Andrea Riseborough"),
                    ("Cate Blanchett", "Cate Blanchett"),
                    ("Michelle Williams", "Michelle Williams"),
                    ("Michelle Yeoh", "Michelle Yeoh"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="animatedfeature",
            field=models.CharField(
                choices=[
                    (
                        "Guillermo del Toro's Pinocchio",
                        "Guillermo del Toro's Pinocchio",
                    ),
                    (
                        "Marcel the Shell with Shoes On",
                        "Marcel the Shell with Shoes On",
                    ),
                    ("Puss in Boots: The Last Wish", "Puss in Boots: The Last Wish"),
                    ("The Sea Beast", "The Sea Beast"),
                    ("Turning Red", "Turning Red"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="animatedshort",
            field=models.CharField(
                choices=[
                    (
                        "The Boy, the Mole, the Fox and the Horse",
                        "The Boy, the Mole, the Fox and the Horse",
                    ),
                    ("The Flying Sailor", "The Flying Sailor"),
                    ("Ice Merchants", "Ice Merchants"),
                    ("My Year of Dicks", "My Year of Dicks"),
                    (
                        "An Ostrich Told Me the World Is Fake and I Think I Believe It",
                        "An Ostrich Told Me the World Is Fake and I Think I Believe It",
                    ),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="bestpicture",
            field=models.CharField(
                choices=[
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("Avatar: The Way of Water", "Avatar: The Way of Water"),
                    ("Elvis", "Elvis"),
                    (
                        "Everything Everywhere All at Once",
                        "Everything Everywhere All at Once",
                    ),
                    ("The Banshees of Inisherin", "The Banshees of Inisherin"),
                    ("The Fabelmans", "The Fabelmans"),
                    ("Top Gun: Maverick", "Top Gun: Maverick"),
                    ("Triangle of Sadness", "Triangle of Sadness"),
                    ("Tar", "Tar"),
                    ("Women Talking", "Women Talking"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="cinematography",
            field=models.CharField(
                choices=[
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    (
                        "Bardo: False Chronicle of a Handful of Truths",
                        "Bardo: False Chronicle of a Handful of Truths",
                    ),
                    ("Elvis", "Elvis"),
                    ("Empire of Light", "Empire of Light"),
                    ("Tar", "Tar"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="costume",
            field=models.CharField(
                choices=[
                    ("Babylon", "Babylon"),
                    (
                        "Black Panther: Wakanda Forever",
                        "Black Panther: Wakanda Forever",
                    ),
                    ("Elvis", "Elvis"),
                    (
                        "Everything Everywhere All at Once",
                        "Everything Everywhere All at Once",
                    ),
                    ("Mrs. Harris Goes to Paris", "Mrs. Harris Goes to Paris"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="directing",
            field=models.CharField(
                choices=[
                    ("The Banshees of Inisherin", "The Banshees of Inisherin"),
                    (
                        "Everything Everywhere All at Once",
                        "Everything Everywhere All at Once",
                    ),
                    ("The Fabelmans", "The Fabelmans"),
                    ("Tar", "Tar"),
                    ("Triangle of Sadness", "Triangle of Sadness"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="docshort",
            field=models.CharField(
                choices=[
                    ("The Elephant Whisperers", "The Elephant Whisperers"),
                    ("Haulout", "Haulout"),
                    ("How Do You Measure a Year?", "How Do You Measure a Year?"),
                    ("The Martha Mitchell Effect", "The Martha Mitchell Effect"),
                    ("Stranger at the Gate", "Stranger at the Gate"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="documentary",
            field=models.CharField(
                choices=[
                    ("All That Breathes", "All That Breathes"),
                    (
                        "All the Beauty and the Bloodshed",
                        "All the Beauty and the Bloodshed",
                    ),
                    ("Fire of Love", "Fire of Love"),
                    ("A House Made of Splinters", "A House Made of Splinters"),
                    ("Navalny", "Navalny"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="fediting",
            field=models.CharField(
                choices=[
                    ("The Banshees of Inisherin", "The Banshees of Inisherin"),
                    ("Elvis", "Elvis"),
                    (
                        "Everything Everywhere All at Once",
                        "Everything Everywhere All at Once",
                    ),
                    ("Top Gun: Maverick", "Top Gun: Maverick"),
                    ("Tar", "Tar"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="foreign",
            field=models.CharField(
                choices=[
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("Argentina, 1985", "Argentina, 1985"),
                    ("Close", "Close"),
                    ("Eo", "Eo"),
                    ("The Quiet Girl", "The Quiet Girl"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="makeupandh",
            field=models.CharField(
                choices=[
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("The Batman", "The Batman"),
                    (
                        "Black Panther: Wakanda Forever",
                        "Black Panther: Wakanda Forever",
                    ),
                    ("Elvis", "Elvis"),
                    ("The Whale", "The Whale"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="mscore",
            field=models.CharField(
                choices=[
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("Babylon", "Babylon"),
                    ("The Banshees of Inisherin", "The Banshees of Inisherin"),
                    (
                        "Everything Everywhere All at Once",
                        "Everything Everywhere All at Once",
                    ),
                    ("The Fabelmans", "The Fabelmans"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="msong",
            field=models.CharField(
                choices=[
                    ("Applause", "Applause"),
                    ("Hold My Hand", "Hold My Hand"),
                    ("Lift Me Up", "Lift Me Up"),
                    ("Naatu Naatu", "Naatu Naatu"),
                    ("This Is a Life", "This Is a Life"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="prodesign",
            field=models.CharField(
                choices=[
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("Avatar: The Way of Water", "Avatar: The Way of Water"),
                    ("Babylon", "Babylon"),
                    ("Elvis", "Elvis"),
                    ("The Fabelmans", "The Fabelmans"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="shortfilm",
            field=models.CharField(
                choices=[
                    ("An Irish Goodbye", "An Irish Goodbye"),
                    ("Ivalu", "Ivalu"),
                    ("Le Pupille", "Le Pupille"),
                    ("Night Ride", "Night Ride"),
                    ("The Red Suitcase", "The Red Suitcase"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="sound",
            field=models.CharField(
                choices=[
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("Avatar: The Way of Water", "Avatar: The Way of Water"),
                    ("The Batman", "The Batman"),
                    ("Elvis", "Elvis"),
                    ("Top Gun: Maverick", "Top Gun: Maverick"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="supactor",
            field=models.CharField(
                choices=[
                    ("Barry Keoghan", "Barry Keoghan"),
                    ("Brendan Gleeson", "Brendan Gleeson"),
                    ("Brian Tyree Henry", "Brian Tyree Henry"),
                    ("Judd Hirsch", "Judd Hirsch"),
                    ("Ke Huy Quan", "Ke Huy Quan"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="supactress",
            field=models.CharField(
                choices=[
                    ("Angela Bassett", "Angela Bassett"),
                    ("Hong Chau", "Hong Chau"),
                    ("Jamie Lee Curtis", "Jamie Lee Curtis"),
                    ("Kerry Condon", "Kerry Condon"),
                    ("Stephanie Hsu", "Stephanie Hsu"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="visualfx",
            field=models.CharField(
                choices=[
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("Avatar: The Way of Water", "Avatar: The Way of Water"),
                    ("The Batman", "The Batman"),
                    (
                        "Black Panther: Wakanda Forever",
                        "Black Panther: Wakanda Forever",
                    ),
                    ("Top Gun: Maverick", "Top Gun: Maverick"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="writingad",
            field=models.CharField(
                choices=[
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("Glass Onion", "Glass Onion"),
                    ("Living", "Living"),
                    ("Top Gun: Maverick", "Top Gun: Maverick"),
                    ("Women Talking", "Women Talking"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="writingor",
            field=models.CharField(
                choices=[
                    (
                        "Everything Everywhere All at Once",
                        "Everything Everywhere All at Once",
                    ),
                    ("The Banshees of Inisherin", "The Banshees of Inisherin"),
                    ("The Fabelmans", "The Fabelmans"),
                    ("Triangle of Sadness", "Triangle of Sadness"),
                    ("Tar", "Tar"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="actor",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("Austin Butler", "Austin Butler"),
                    ("Bill Nighy", "Bill Nighy"),
                    ("Brendan Fraser", "Brendan Fraser"),
                    ("Colin Farrell", "Colin Farrell"),
                    ("Paul Mescal", "Paul Mescal"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="actress",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("Ana de Armas", "Ana de Armas"),
                    ("Andrea Riseborough", "Andrea Riseborough"),
                    ("Cate Blanchett", "Cate Blanchett"),
                    ("Michelle Williams", "Michelle Williams"),
                    ("Michelle Yeoh", "Michelle Yeoh"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="animatedfeature",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    (
                        "Guillermo del Toro's Pinocchio",
                        "Guillermo del Toro's Pinocchio",
                    ),
                    (
                        "Marcel the Shell with Shoes On",
                        "Marcel the Shell with Shoes On",
                    ),
                    ("Puss in Boots: The Last Wish", "Puss in Boots: The Last Wish"),
                    ("The Sea Beast", "The Sea Beast"),
                    ("Turning Red", "Turning Red"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="animatedshort",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    (
                        "The Boy, the Mole, the Fox and the Horse",
                        "The Boy, the Mole, the Fox and the Horse",
                    ),
                    ("The Flying Sailor", "The Flying Sailor"),
                    ("Ice Merchants", "Ice Merchants"),
                    ("My Year of Dicks", "My Year of Dicks"),
                    (
                        "An Ostrich Told Me the World Is Fake and I Think I Believe It",
                        "An Ostrich Told Me the World Is Fake and I Think I Believe It",
                    ),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="bestpicture",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("Avatar: The Way of Water", "Avatar: The Way of Water"),
                    ("Elvis", "Elvis"),
                    (
                        "Everything Everywhere All at Once",
                        "Everything Everywhere All at Once",
                    ),
                    ("The Banshees of Inisherin", "The Banshees of Inisherin"),
                    ("The Fabelmans", "The Fabelmans"),
                    ("Top Gun: Maverick", "Top Gun: Maverick"),
                    ("Triangle of Sadness", "Triangle of Sadness"),
                    ("Tar", "Tar"),
                    ("Women Talking", "Women Talking"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="cinematography",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    (
                        "Bardo: False Chronicle of a Handful of Truths",
                        "Bardo: False Chronicle of a Handful of Truths",
                    ),
                    ("Elvis", "Elvis"),
                    ("Empire of Light", "Empire of Light"),
                    ("Tar", "Tar"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="costume",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("Babylon", "Babylon"),
                    (
                        "Black Panther: Wakanda Forever",
                        "Black Panther: Wakanda Forever",
                    ),
                    ("Elvis", "Elvis"),
                    (
                        "Everything Everywhere All at Once",
                        "Everything Everywhere All at Once",
                    ),
                    ("Mrs. Harris Goes to Paris", "Mrs. Harris Goes to Paris"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="directing",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("The Banshees of Inisherin", "The Banshees of Inisherin"),
                    (
                        "Everything Everywhere All at Once",
                        "Everything Everywhere All at Once",
                    ),
                    ("The Fabelmans", "The Fabelmans"),
                    ("Tar", "Tar"),
                    ("Triangle of Sadness", "Triangle of Sadness"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="docshort",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("The Elephant Whisperers", "The Elephant Whisperers"),
                    ("Haulout", "Haulout"),
                    ("How Do You Measure a Year?", "How Do You Measure a Year?"),
                    ("The Martha Mitchell Effect", "The Martha Mitchell Effect"),
                    ("Stranger at the Gate", "Stranger at the Gate"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="documentary",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("All That Breathes", "All That Breathes"),
                    (
                        "All the Beauty and the Bloodshed",
                        "All the Beauty and the Bloodshed",
                    ),
                    ("Fire of Love", "Fire of Love"),
                    ("A House Made of Splinters", "A House Made of Splinters"),
                    ("Navalny", "Navalny"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="fediting",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("The Banshees of Inisherin", "The Banshees of Inisherin"),
                    ("Elvis", "Elvis"),
                    (
                        "Everything Everywhere All at Once",
                        "Everything Everywhere All at Once",
                    ),
                    ("Top Gun: Maverick", "Top Gun: Maverick"),
                    ("Tar", "Tar"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="foreign",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("Argentina, 1985", "Argentina, 1985"),
                    ("Close", "Close"),
                    ("Eo", "Eo"),
                    ("The Quiet Girl", "The Quiet Girl"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="makeupandh",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("The Batman", "The Batman"),
                    (
                        "Black Panther: Wakanda Forever",
                        "Black Panther: Wakanda Forever",
                    ),
                    ("Elvis", "Elvis"),
                    ("The Whale", "The Whale"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="mscore",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("Babylon", "Babylon"),
                    ("The Banshees of Inisherin", "The Banshees of Inisherin"),
                    (
                        "Everything Everywhere All at Once",
                        "Everything Everywhere All at Once",
                    ),
                    ("The Fabelmans", "The Fabelmans"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="msong",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("Applause", "Applause"),
                    ("Hold My Hand", "Hold My Hand"),
                    ("Lift Me Up", "Lift Me Up"),
                    ("Naatu Naatu", "Naatu Naatu"),
                    ("This Is a Life", "This Is a Life"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="prodesign",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("Avatar: The Way of Water", "Avatar: The Way of Water"),
                    ("Babylon", "Babylon"),
                    ("Elvis", "Elvis"),
                    ("The Fabelmans", "The Fabelmans"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="shortfilm",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("An Irish Goodbye", "An Irish Goodbye"),
                    ("Ivalu", "Ivalu"),
                    ("Le Pupille", "Le Pupille"),
                    ("Night Ride", "Night Ride"),
                    ("The Red Suitcase", "The Red Suitcase"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="sound",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("Avatar: The Way of Water", "Avatar: The Way of Water"),
                    ("The Batman", "The Batman"),
                    ("Elvis", "Elvis"),
                    ("Top Gun: Maverick", "Top Gun: Maverick"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="supactor",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("Barry Keoghan", "Barry Keoghan"),
                    ("Brendan Gleeson", "Brendan Gleeson"),
                    ("Brian Tyree Henry", "Brian Tyree Henry"),
                    ("Judd Hirsch", "Judd Hirsch"),
                    ("Ke Huy Quan", "Ke Huy Quan"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="supactress",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("Angela Bassett", "Angela Bassett"),
                    ("Hong Chau", "Hong Chau"),
                    ("Jamie Lee Curtis", "Jamie Lee Curtis"),
                    ("Kerry Condon", "Kerry Condon"),
                    ("Stephanie Hsu", "Stephanie Hsu"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="visualfx",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("Avatar: The Way of Water", "Avatar: The Way of Water"),
                    ("The Batman", "The Batman"),
                    (
                        "Black Panther: Wakanda Forever",
                        "Black Panther: Wakanda Forever",
                    ),
                    ("Top Gun: Maverick", "Top Gun: Maverick"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="writingad",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    (
                        "All Quiet on the Western Front",
                        "All Quiet on the Western Front",
                    ),
                    ("Glass Onion", "Glass Onion"),
                    ("Living", "Living"),
                    ("Top Gun: Maverick", "Top Gun: Maverick"),
                    ("Women Talking", "Women Talking"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="writingor",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    (
                        "Everything Everywhere All at Once",
                        "Everything Everywhere All at Once",
                    ),
                    ("The Banshees of Inisherin", "The Banshees of Inisherin"),
                    ("The Fabelmans", "The Fabelmans"),
                    ("Triangle of Sadness", "Triangle of Sadness"),
                    ("Tar", "Tar"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
    ]
