# Generated by Django 4.1.4 on 2023-03-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oscarsapp", "0010_oscarballot_hidden_umslballot_hidden_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oscarballot",
            name="user",
            field=models.CharField(default="NA", max_length=100),
        ),
    ]
