# Generated by Django 4.1.4 on 2024-03-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oscarsapp", "0011_oscarballot_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oscarballot",
            name="actor",
            field=models.CharField(
                choices=[
                    ("Bradley Cooper", "Bradley Cooper"),
                    ("Colman Domingo", "Colman Domingo"),
                    ("Paul Giamatti", "Paul Giamatti"),
                    ("Cillian Murphy", "Cillian Murphy"),
                    ("Jeffrey Wright", "Jeffrey Wright"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="actress",
            field=models.CharField(
                choices=[
                    ("Annette Bening", "Annette Bening"),
                    ("Lily Gladstone", "Lily Gladstone"),
                    ("Sandra Huller", "Sandra Huller"),
                    ("Carey Mulligan", "Carey Mulligan"),
                    ("Emma Stone", "Emma Stone"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="animatedfeature",
            field=models.CharField(
                choices=[
                    ("The Boy and the Heron", "The Boy and the Heron"),
                    ("Elemental", "Elemental"),
                    ("Nimona", "Nimona"),
                    (
                        "Spider-Man: Across the Spider-Verse",
                        "Spider-Man: Across the Spider-Verse",
                    ),
                    ("Turning Red", "Turning Red"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="animatedshort",
            field=models.CharField(
                choices=[
                    ("Letter to a Pig", "Letter to a Pig"),
                    ("Ninety-Five Senses", "Ninety-Five Senses"),
                    ("Our Uniform", "Our Uniform"),
                    ("Pachyderme", "Pachyderme"),
                    (
                        "War Is Over! Inspired by the Music of John & Yoko",
                        "War Is Over! Inspired by the Music of John & Yoko",
                    ),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="bestpicture",
            field=models.CharField(
                choices=[
                    ("American Fiction", "American Fiction"),
                    ("Anatomy of a Fall", "Anatomy of a Fall"),
                    ("Barbie", "Barbie"),
                    ("The Holdovers", "The Holdovers"),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Maestro", "Maestro"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Past Lives", "Past Lives"),
                    ("Poor Things", "Poor Things"),
                    ("The Zone of Interest", "The Zone of Interest"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="cinematography",
            field=models.CharField(
                choices=[
                    ("El Conde", "El Conde"),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Maestro", "Maestro"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Poor Things", "Poor Things"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="costume",
            field=models.CharField(
                choices=[
                    ("Barbie", "Barbie"),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Napoleon", "Napoleon"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Poor Things", "Poor Things"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="directing",
            field=models.CharField(
                choices=[
                    ("The Zone of Interest", "The Zone of Interest"),
                    ("Poor Things", "Poor Things"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Anatomy of a Fall", "Anatomy of a Fall"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="docshort",
            field=models.CharField(
                choices=[
                    ("The ABCs of Book Banning", "The ABCs of Book Banning"),
                    ("The Barber of Little Rock", "The Barber of Little Rock"),
                    ("Island in Between", "Island in Between"),
                    ("The Last Repair Shop", "The Last Repair Shop"),
                    ("Nai Nai & Wai Po", "Nai Nai & Wai Po"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="documentary",
            field=models.CharField(
                choices=[
                    (
                        "Bobi Wine: The People's President",
                        "Bobi Wine: The People's President",
                    ),
                    ("The Eternal Memory", "The Eternal Memory"),
                    ("Four Daughters", "Four Daughters"),
                    ("To Kill a Tiger", "To Kill a Tiger"),
                    ("20 Days in Mariupol", "20 Days in Mariupol"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="fediting",
            field=models.CharField(
                choices=[
                    ("Anatomy of a Fall", "Anatomy of a Fall"),
                    ("The Holdovers", "The Holdovers"),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Poor Things", "Poor Things"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="foreign",
            field=models.CharField(
                choices=[
                    ("Io Capitano", "Io Capitano"),
                    ("Perfect Days", "Perfect Days"),
                    ("Society of the Snow", "Society of the Snow"),
                    ("The Teachers' Lounge", "The Teachers' Lounge"),
                    ("The Zone of Interest", "The Zone of Interest"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="makeupandh",
            field=models.CharField(
                choices=[
                    ("Golda", "Golda"),
                    ("Maestro", "Maestro"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Poor Things", "Poor Things"),
                    ("Society of the Snow", "Society of the Snow"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="mscore",
            field=models.CharField(
                choices=[
                    ("American Fiction", "American Fiction"),
                    (
                        "Indiana Jones and the Dial of Destiny",
                        "Indiana Jones and the Dial of Destiny",
                    ),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Poor Things", "Poor Things"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="msong",
            field=models.CharField(
                choices=[
                    ("The Fire Inside", "The Fire Inside"),
                    ("I'm Just Ken", "I'm Just Ken"),
                    ("It Never Went Away", "It Never Went Away"),
                    (
                        "Wahzhazhe (A Song For My People)",
                        "Wahzhazhe (A Song For My People)",
                    ),
                    ("What Was I Made For?", "What Was I Made For?"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="prodesign",
            field=models.CharField(
                choices=[
                    ("Barbie", "Barbie"),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Napoleon", "Napoleon"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Poor Things", "Poor Things"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="shortfilm",
            field=models.CharField(
                choices=[
                    ("The After", "The After"),
                    ("Invincible", "Invincible"),
                    ("Knight of Fortune", "Knight of Fortune"),
                    ("Red, White, and Blue", "Red, White, and Blue"),
                    (
                        "The Wonderful Story of Henry Sugar",
                        "The Wonderful Story of Henry Sugar",
                    ),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="sound",
            field=models.CharField(
                choices=[
                    ("The Creator", "The Creator"),
                    ("Maestro", "Maestro"),
                    (
                        "Mission: Impossible - Dead Reckoning Part One",
                        "Mission: Impossible - Dead Reckoning Part One",
                    ),
                    ("Oppenheimer", "Oppenheimer"),
                    ("The Zone of Interest", "The Zone of Interest"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="supactor",
            field=models.CharField(
                choices=[
                    ("Sterling K. Brown", "Sterling K. Brown"),
                    ("Robert De Niro", "Robert De Niro"),
                    ("Robert Downey Jr.", "Robert Downey Jr."),
                    ("Ryan Gosling", "Ryan Gosling"),
                    ("Mark Ruffalo", "Mark Ruffalo"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="supactress",
            field=models.CharField(
                choices=[
                    ("Emily Blunt", "Emily Blunt"),
                    ("Danielle Brooks", "Danielle Brooks"),
                    ("America Ferrera", "America Ferrera"),
                    ("Jody Foster", "Jody Foster"),
                    ("Da'Vine Joy Randolph", "Da'Vine Joy Randolph"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="visualfx",
            field=models.CharField(
                choices=[
                    ("The Creator", "The Creator"),
                    ("Godzilla Minus One", "Godzilla Minus One"),
                    (
                        "Guardians of the Galaxy Vol. 3",
                        "Guardians of the Galaxy Vol. 3",
                    ),
                    (
                        "Mission: Impossible - Dead Reckoning Part One",
                        "Mission: Impossible - Dead Reckoning Part One",
                    ),
                    ("Napoleon", "Napoleon"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="writingad",
            field=models.CharField(
                choices=[
                    ("American Fiction", "American Fiction"),
                    ("Barbie", "Barbie"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Poor Things", "Poor Things"),
                    ("The Zone of Interest", "The Zone of Interest"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="writingor",
            field=models.CharField(
                choices=[
                    ("Anatomy of a Fall", "Anatomy of a Fall"),
                    ("The Holdovers", "The Holdovers"),
                    ("Maestro", "Maestro"),
                    ("May December", "May December"),
                    ("Past Lives", "Past Lives"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="actor",
            field=models.CharField(
                choices=[
                    ("Bradley Cooper", "Bradley Cooper"),
                    ("Colman Domingo", "Colman Domingo"),
                    ("Paul Giamatti", "Paul Giamatti"),
                    ("Cillian Murphy", "Cillian Murphy"),
                    ("Jeffrey Wright", "Jeffrey Wright"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="actress",
            field=models.CharField(
                choices=[
                    ("Annette Bening", "Annette Bening"),
                    ("Lily Gladstone", "Lily Gladstone"),
                    ("Sandra Huller", "Sandra Huller"),
                    ("Carey Mulligan", "Carey Mulligan"),
                    ("Emma Stone", "Emma Stone"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="animatedfeature",
            field=models.CharField(
                choices=[
                    ("The Boy and the Heron", "The Boy and the Heron"),
                    ("Elemental", "Elemental"),
                    ("Nimona", "Nimona"),
                    (
                        "Spider-Man: Across the Spider-Verse",
                        "Spider-Man: Across the Spider-Verse",
                    ),
                    ("Turning Red", "Turning Red"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="animatedshort",
            field=models.CharField(
                choices=[
                    ("Letter to a Pig", "Letter to a Pig"),
                    ("Ninety-Five Senses", "Ninety-Five Senses"),
                    ("Our Uniform", "Our Uniform"),
                    ("Pachyderme", "Pachyderme"),
                    (
                        "War Is Over! Inspired by the Music of John & Yoko",
                        "War Is Over! Inspired by the Music of John & Yoko",
                    ),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="bestpicture",
            field=models.CharField(
                choices=[
                    ("American Fiction", "American Fiction"),
                    ("Anatomy of a Fall", "Anatomy of a Fall"),
                    ("Barbie", "Barbie"),
                    ("The Holdovers", "The Holdovers"),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Maestro", "Maestro"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Past Lives", "Past Lives"),
                    ("Poor Things", "Poor Things"),
                    ("The Zone of Interest", "The Zone of Interest"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="cinematography",
            field=models.CharField(
                choices=[
                    ("El Conde", "El Conde"),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Maestro", "Maestro"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Poor Things", "Poor Things"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="costume",
            field=models.CharField(
                choices=[
                    ("Barbie", "Barbie"),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Napoleon", "Napoleon"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Poor Things", "Poor Things"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="directing",
            field=models.CharField(
                choices=[
                    ("The Zone of Interest", "The Zone of Interest"),
                    ("Poor Things", "Poor Things"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Anatomy of a Fall", "Anatomy of a Fall"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="docshort",
            field=models.CharField(
                choices=[
                    ("The ABCs of Book Banning", "The ABCs of Book Banning"),
                    ("The Barber of Little Rock", "The Barber of Little Rock"),
                    ("Island in Between", "Island in Between"),
                    ("The Last Repair Shop", "The Last Repair Shop"),
                    ("Nai Nai & Wai Po", "Nai Nai & Wai Po"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="documentary",
            field=models.CharField(
                choices=[
                    (
                        "Bobi Wine: The People's President",
                        "Bobi Wine: The People's President",
                    ),
                    ("The Eternal Memory", "The Eternal Memory"),
                    ("Four Daughters", "Four Daughters"),
                    ("To Kill a Tiger", "To Kill a Tiger"),
                    ("20 Days in Mariupol", "20 Days in Mariupol"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="fediting",
            field=models.CharField(
                choices=[
                    ("Anatomy of a Fall", "Anatomy of a Fall"),
                    ("The Holdovers", "The Holdovers"),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Poor Things", "Poor Things"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="foreign",
            field=models.CharField(
                choices=[
                    ("Io Capitano", "Io Capitano"),
                    ("Perfect Days", "Perfect Days"),
                    ("Society of the Snow", "Society of the Snow"),
                    ("The Teachers' Lounge", "The Teachers' Lounge"),
                    ("The Zone of Interest", "The Zone of Interest"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="makeupandh",
            field=models.CharField(
                choices=[
                    ("Golda", "Golda"),
                    ("Maestro", "Maestro"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Poor Things", "Poor Things"),
                    ("Society of the Snow", "Society of the Snow"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="mscore",
            field=models.CharField(
                choices=[
                    ("American Fiction", "American Fiction"),
                    (
                        "Indiana Jones and the Dial of Destiny",
                        "Indiana Jones and the Dial of Destiny",
                    ),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Poor Things", "Poor Things"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="msong",
            field=models.CharField(
                choices=[
                    ("The Fire Inside", "The Fire Inside"),
                    ("I'm Just Ken", "I'm Just Ken"),
                    ("It Never Went Away", "It Never Went Away"),
                    (
                        "Wahzhazhe (A Song For My People)",
                        "Wahzhazhe (A Song For My People)",
                    ),
                    ("What Was I Made For?", "What Was I Made For?"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="prodesign",
            field=models.CharField(
                choices=[
                    ("Barbie", "Barbie"),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Napoleon", "Napoleon"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Poor Things", "Poor Things"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="shortfilm",
            field=models.CharField(
                choices=[
                    ("The After", "The After"),
                    ("Invincible", "Invincible"),
                    ("Knight of Fortune", "Knight of Fortune"),
                    ("Red, White, and Blue", "Red, White, and Blue"),
                    (
                        "The Wonderful Story of Henry Sugar",
                        "The Wonderful Story of Henry Sugar",
                    ),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="sound",
            field=models.CharField(
                choices=[
                    ("The Creator", "The Creator"),
                    ("Maestro", "Maestro"),
                    (
                        "Mission: Impossible - Dead Reckoning Part One",
                        "Mission: Impossible - Dead Reckoning Part One",
                    ),
                    ("Oppenheimer", "Oppenheimer"),
                    ("The Zone of Interest", "The Zone of Interest"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="supactor",
            field=models.CharField(
                choices=[
                    ("Sterling K. Brown", "Sterling K. Brown"),
                    ("Robert De Niro", "Robert De Niro"),
                    ("Robert Downey Jr.", "Robert Downey Jr."),
                    ("Ryan Gosling", "Ryan Gosling"),
                    ("Mark Ruffalo", "Mark Ruffalo"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="supactress",
            field=models.CharField(
                choices=[
                    ("Emily Blunt", "Emily Blunt"),
                    ("Danielle Brooks", "Danielle Brooks"),
                    ("America Ferrera", "America Ferrera"),
                    ("Jody Foster", "Jody Foster"),
                    ("Da'Vine Joy Randolph", "Da'Vine Joy Randolph"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="visualfx",
            field=models.CharField(
                choices=[
                    ("The Creator", "The Creator"),
                    ("Godzilla Minus One", "Godzilla Minus One"),
                    (
                        "Guardians of the Galaxy Vol. 3",
                        "Guardians of the Galaxy Vol. 3",
                    ),
                    (
                        "Mission: Impossible - Dead Reckoning Part One",
                        "Mission: Impossible - Dead Reckoning Part One",
                    ),
                    ("Napoleon", "Napoleon"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="writingad",
            field=models.CharField(
                choices=[
                    ("American Fiction", "American Fiction"),
                    ("Barbie", "Barbie"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Poor Things", "Poor Things"),
                    ("The Zone of Interest", "The Zone of Interest"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="writingor",
            field=models.CharField(
                choices=[
                    ("Anatomy of a Fall", "Anatomy of a Fall"),
                    ("The Holdovers", "The Holdovers"),
                    ("Maestro", "Maestro"),
                    ("May December", "May December"),
                    ("Past Lives", "Past Lives"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="actor",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("Bradley Cooper", "Bradley Cooper"),
                    ("Colman Domingo", "Colman Domingo"),
                    ("Paul Giamatti", "Paul Giamatti"),
                    ("Cillian Murphy", "Cillian Murphy"),
                    ("Jeffrey Wright", "Jeffrey Wright"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="actress",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("Annette Bening", "Annette Bening"),
                    ("Lily Gladstone", "Lily Gladstone"),
                    ("Sandra Huller", "Sandra Huller"),
                    ("Carey Mulligan", "Carey Mulligan"),
                    ("Emma Stone", "Emma Stone"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="animatedfeature",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("The Boy and the Heron", "The Boy and the Heron"),
                    ("Elemental", "Elemental"),
                    ("Nimona", "Nimona"),
                    (
                        "Spider-Man: Across the Spider-Verse",
                        "Spider-Man: Across the Spider-Verse",
                    ),
                    ("Turning Red", "Turning Red"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="animatedshort",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("Letter to a Pig", "Letter to a Pig"),
                    ("Ninety-Five Senses", "Ninety-Five Senses"),
                    ("Our Uniform", "Our Uniform"),
                    ("Pachyderme", "Pachyderme"),
                    (
                        "War Is Over! Inspired by the Music of John & Yoko",
                        "War Is Over! Inspired by the Music of John & Yoko",
                    ),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="bestpicture",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("American Fiction", "American Fiction"),
                    ("Anatomy of a Fall", "Anatomy of a Fall"),
                    ("Barbie", "Barbie"),
                    ("The Holdovers", "The Holdovers"),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Maestro", "Maestro"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Past Lives", "Past Lives"),
                    ("Poor Things", "Poor Things"),
                    ("The Zone of Interest", "The Zone of Interest"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="cinematography",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("El Conde", "El Conde"),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Maestro", "Maestro"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Poor Things", "Poor Things"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="costume",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("Barbie", "Barbie"),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Napoleon", "Napoleon"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Poor Things", "Poor Things"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="directing",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("The Zone of Interest", "The Zone of Interest"),
                    ("Poor Things", "Poor Things"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Anatomy of a Fall", "Anatomy of a Fall"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="docshort",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("The ABCs of Book Banning", "The ABCs of Book Banning"),
                    ("The Barber of Little Rock", "The Barber of Little Rock"),
                    ("Island in Between", "Island in Between"),
                    ("The Last Repair Shop", "The Last Repair Shop"),
                    ("Nai Nai & Wai Po", "Nai Nai & Wai Po"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="documentary",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    (
                        "Bobi Wine: The People's President",
                        "Bobi Wine: The People's President",
                    ),
                    ("The Eternal Memory", "The Eternal Memory"),
                    ("Four Daughters", "Four Daughters"),
                    ("To Kill a Tiger", "To Kill a Tiger"),
                    ("20 Days in Mariupol", "20 Days in Mariupol"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="fediting",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("Anatomy of a Fall", "Anatomy of a Fall"),
                    ("The Holdovers", "The Holdovers"),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Poor Things", "Poor Things"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="foreign",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("Io Capitano", "Io Capitano"),
                    ("Perfect Days", "Perfect Days"),
                    ("Society of the Snow", "Society of the Snow"),
                    ("The Teachers' Lounge", "The Teachers' Lounge"),
                    ("The Zone of Interest", "The Zone of Interest"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="makeupandh",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("Golda", "Golda"),
                    ("Maestro", "Maestro"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Poor Things", "Poor Things"),
                    ("Society of the Snow", "Society of the Snow"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="mscore",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("American Fiction", "American Fiction"),
                    (
                        "Indiana Jones and the Dial of Destiny",
                        "Indiana Jones and the Dial of Destiny",
                    ),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Poor Things", "Poor Things"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="msong",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("The Fire Inside", "The Fire Inside"),
                    ("I'm Just Ken", "I'm Just Ken"),
                    ("It Never Went Away", "It Never Went Away"),
                    (
                        "Wahzhazhe (A Song For My People)",
                        "Wahzhazhe (A Song For My People)",
                    ),
                    ("What Was I Made For?", "What Was I Made For?"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="prodesign",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("Barbie", "Barbie"),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Napoleon", "Napoleon"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Poor Things", "Poor Things"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="shortfilm",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("The After", "The After"),
                    ("Invincible", "Invincible"),
                    ("Knight of Fortune", "Knight of Fortune"),
                    ("Red, White, and Blue", "Red, White, and Blue"),
                    (
                        "The Wonderful Story of Henry Sugar",
                        "The Wonderful Story of Henry Sugar",
                    ),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="sound",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("The Creator", "The Creator"),
                    ("Maestro", "Maestro"),
                    (
                        "Mission: Impossible - Dead Reckoning Part One",
                        "Mission: Impossible - Dead Reckoning Part One",
                    ),
                    ("Oppenheimer", "Oppenheimer"),
                    ("The Zone of Interest", "The Zone of Interest"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="supactor",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("Sterling K. Brown", "Sterling K. Brown"),
                    ("Robert De Niro", "Robert De Niro"),
                    ("Robert Downey Jr.", "Robert Downey Jr."),
                    ("Ryan Gosling", "Ryan Gosling"),
                    ("Mark Ruffalo", "Mark Ruffalo"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="supactress",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("Emily Blunt", "Emily Blunt"),
                    ("Danielle Brooks", "Danielle Brooks"),
                    ("America Ferrera", "America Ferrera"),
                    ("Jody Foster", "Jody Foster"),
                    ("Da'Vine Joy Randolph", "Da'Vine Joy Randolph"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="visualfx",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("The Creator", "The Creator"),
                    ("Godzilla Minus One", "Godzilla Minus One"),
                    (
                        "Guardians of the Galaxy Vol. 3",
                        "Guardians of the Galaxy Vol. 3",
                    ),
                    (
                        "Mission: Impossible - Dead Reckoning Part One",
                        "Mission: Impossible - Dead Reckoning Part One",
                    ),
                    ("Napoleon", "Napoleon"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="writingad",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("American Fiction", "American Fiction"),
                    ("Barbie", "Barbie"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Poor Things", "Poor Things"),
                    ("The Zone of Interest", "The Zone of Interest"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="writingor",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("Anatomy of a Fall", "Anatomy of a Fall"),
                    ("The Holdovers", "The Holdovers"),
                    ("Maestro", "Maestro"),
                    ("May December", "May December"),
                    ("Past Lives", "Past Lives"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
    ]
