# Generated by Django 4.1.4 on 2024-03-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "oscarsapp",
            "0012_alter_oscarballot_actor_alter_oscarballot_actress_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="umslballot",
            name="user",
            field=models.CharField(default="NA", max_length=100),
        ),
    ]
