# Generated by Django 4.1.4 on 2025-02-09 02:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("oscarsapp", "0013_umslballot_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="NA", max_length=100)),
                ("image_url", models.CharField(default="NA", max_length=100)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Nomination",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(default="NA", max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="animatedfeature",
            field=models.CharField(
                choices=[
                    ("The Boy and the Heron", "The Boy and the Heron"),
                    ("Elemental", "Elemental"),
                    ("Nimona", "Nimona"),
                    (
                        "Spider-Man: Across the Spider-Verse",
                        "Spider-Man: Across the Spider-Verse",
                    ),
                    ("Robot Dreams", "Robot Dreams"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="oscarballot",
            name="bestpicture",
            field=models.CharField(
                choices=[
                    ("Anora", "Anora"),
                    ("Anatomy of a Fall", "Anatomy of a Fall"),
                    ("Barbie", "Barbie"),
                    ("The Holdovers", "The Holdovers"),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Maestro", "Maestro"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Past Lives", "Past Lives"),
                    ("Poor Things", "Poor Things"),
                    ("The Zone of Interest", "The Zone of Interest"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="animatedfeature",
            field=models.CharField(
                choices=[
                    ("The Boy and the Heron", "The Boy and the Heron"),
                    ("Elemental", "Elemental"),
                    ("Nimona", "Nimona"),
                    (
                        "Spider-Man: Across the Spider-Verse",
                        "Spider-Man: Across the Spider-Verse",
                    ),
                    ("Robot Dreams", "Robot Dreams"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="umslballot",
            name="bestpicture",
            field=models.CharField(
                choices=[
                    ("Anora", "Anora"),
                    ("Anatomy of a Fall", "Anatomy of a Fall"),
                    ("Barbie", "Barbie"),
                    ("The Holdovers", "The Holdovers"),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Maestro", "Maestro"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Past Lives", "Past Lives"),
                    ("Poor Things", "Poor Things"),
                    ("The Zone of Interest", "The Zone of Interest"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="animatedfeature",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("The Boy and the Heron", "The Boy and the Heron"),
                    ("Elemental", "Elemental"),
                    ("Nimona", "Nimona"),
                    (
                        "Spider-Man: Across the Spider-Verse",
                        "Spider-Man: Across the Spider-Verse",
                    ),
                    ("Robot Dreams", "Robot Dreams"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="winners",
            name="bestpicture",
            field=models.CharField(
                choices=[
                    ("tbd", "tbd"),
                    ("Anora", "Anora"),
                    ("Anatomy of a Fall", "Anatomy of a Fall"),
                    ("Barbie", "Barbie"),
                    ("The Holdovers", "The Holdovers"),
                    ("Killers of the Flower Moon", "Killers of the Flower Moon"),
                    ("Maestro", "Maestro"),
                    ("Oppenheimer", "Oppenheimer"),
                    ("Past Lives", "Past Lives"),
                    ("Poor Things", "Poor Things"),
                    ("The Zone of Interest", "The Zone of Interest"),
                ],
                default="NA",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="NA", max_length=100)),
                (
                    "winner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oscarsapp.movie",
                    ),
                ),
            ],
        ),
    ]
