# Generated by Django 4.1.4 on 2025-02-09 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "oscarsapp",
            "0014_movie_nomination_alter_oscarballot_animatedfeature_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="image_url",
        ),
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="nomination",
            name="movie",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="oscarsapp.movie",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="winner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="oscarsapp.movie",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="nomination",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="oscarsapp.category",
            ),
        ),
    ]
