# Generated by Django 4.1.4 on 2025-02-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "oscarsapp",
            "0015_remove_movie_image_url_movie_image_nomination_movie_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="shortname",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(upload_to="poster"),
        ),
    ]
