# Generated by Django 4.1.4 on 2025-02-10 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oscarsapp", "0017_category_nominations_alter_category_winner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="nominations",
        ),
    ]
