# Generated by Django 4.1.4 on 2025-02-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oscarsapp", "0018_remove_category_nominations"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomination",
            name="subtitle",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="nomination",
            name="url",
            field=models.CharField(default="", max_length=100),
        ),
    ]
