# Generated by Django 4.1.4 on 2025-02-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oscarsapp", "0019_nomination_subtitle_nomination_url"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Movie",
            new_name="Nominee",
        ),
        migrations.RenameField(
            model_name="nomination",
            old_name="movie",
            new_name="nominee",
        ),
    ]
