# Generated by Django 4.1.4 on 2025-02-16 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oscarsapp", "0021_pick_delete_umslballot_delete_winners_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="oscarballot",
            new_name="Ballot",
        ),
    ]
