# Generated by Django 4.1.4 on 2025-02-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oscarsapp", "0022_rename_oscarballot_ballot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wizard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=False)),
            ],
        ),
    ]
