# Generated by Django 4.1.4 on 2025-02-16 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oscarsapp", "0023_wizard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winner",
                to="oscarsapp.nomination",
            ),
        ),
    ]
