# Generated by Django 4.1.4 on 2025-02-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oscarsapp", "0024_alter_category_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="wizard",
            name="lauer_hash",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="wizard",
            name="umsl_hash",
            field=models.CharField(default="", max_length=100),
        ),
    ]
