# Generated by Django 4.1.4 on 2025-02-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oscarsapp", "0025_wizard_lauer_hash_wizard_umsl_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomination",
            name="subtitle",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="nomination",
            name="url",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
