# Generated by Django 4.1.4 on 2025-02-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oscarsapp", "0026_alter_nomination_subtitle_alter_nomination_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
