# Generated by Django 2.1.4 on 2020-09-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeopardyboard',
            name='answer',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AddField(
            model_name='jeopardyboard',
            name='roundno',
            field=models.CharField(default='single', max_length=6),
        ),
    ]
