# Generated by Django 2.1.4 on 2020-09-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0002_auto_20200926_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jeopardyboard',
            old_name='roundno',
            new_name='jround',
        ),
    ]
