# Generated by Django 2.1.4 on 2020-09-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0003_auto_20200926_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeopardyboard',
            name='catname',
            field=models.CharField(default='???', max_length=100),
        ),
    ]
