# Generated by Django 2.1.4 on 2020-09-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0004_jeopardyboard_catname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeopardyboard',
            name='category',
            field=models.CharField(default='cat1', max_length=5),
        ),
    ]
