# Generated by Django 2.1.4 on 2020-09-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0005_auto_20200926_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeopardyboard',
            name='isdouble',
            field=models.BooleanField(default=False),
        ),
    ]
