# Generated by Django 2.1.4 on 2020-10-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0006_jeopardyboard_isdouble'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeopardyboard',
            name='question',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
