# Generated by Django 2.0.2 on 2020-11-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0007_jeopardyboard_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeopardyboard',
            name='game',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
