# Generated by Django 2.1.4 on 2020-12-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0008_jeopardyboard_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(default='default', max_length=100)),
                ('jround', models.CharField(default='single', max_length=6)),
                ('category', models.CharField(default='cat1', max_length=5)),
                ('catname', models.CharField(default='???', max_length=100)),
            ],
        ),
    ]
