# Generated by Django 2.1.4 on 2020-12-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0009_categorytitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='finaljeopardy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(default='default', max_length=100)),
                ('catname', models.CharField(default='???', max_length=100)),
                ('answer', models.CharField(default='none', max_length=300)),
                ('question', models.CharField(default='none', max_length=100)),
            ],
        ),
    ]
