# Generated by Django 2.1.4 on 2021-01-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0011_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ct',
            field=models.BooleanField(default=False),
        ),
    ]
