# Generated by Django 2.1.4 on 2021-02-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0012_team_ct'),
    ]

    operations = [
        migrations.CreateModel(
            name='wizard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField(default=1)),
            ],
        ),
    ]
