# Generated by Django 4.1.4 on 2023-01-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jeopardy", "0013_wizard"),
    ]

    operations = [
        migrations.CreateModel(
            name="game",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gname", models.CharField(max_length=100)),
                ("creator", models.CharField(max_length=100)),
                ("created", models.DateField(auto_now_add=True)),
                ("modified", models.DateField(auto_now=True)),
            ],
        ),
    ]
