# Generated by Django 2.1.4 on 2019-01-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceccevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('month', models.CharField(max_length=10)),
                ('dayno', models.CharField(max_length=2)),
                ('weekday', models.CharField(max_length=10)),
            ],
        ),
    ]
