# Generated by Django 2.1.4 on 2019-01-06 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0002_ceccevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ceccevent',
            old_name='cname',
            new_name='breakfast',
        ),
        migrations.RemoveField(
            model_name='ceccevent',
            name='dayno',
        ),
        migrations.RemoveField(
            model_name='ceccevent',
            name='month',
        ),
        migrations.AddField(
            model_name='ceccevent',
            name='lunch',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ceccevent',
            name='snack',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
