# Generated by Django 2.1.4 on 2019-01-08 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0003_auto_20190106_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceccevent',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
