# Generated by Django 2.1.4 on 2019-01-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0004_ceccevent_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ceccevent',
            old_name='Date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='ceccevent',
            name='weekday',
        ),
    ]
