# Generated by Django 2.1.4 on 2019-01-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0005_auto_20190108_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceccevent',
            name='date',
        ),
        migrations.AddField(
            model_name='ceccevent',
            name='week',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ceccevent',
            name='weekday',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], default='NOD', max_length=3),
        ),
    ]
