# Generated by Django 2.1.4 on 2019-01-10 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0006_auto_20190108_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ceccevent',
            name='weekday',
            field=models.CharField(choices=[('AMON', 'Monday'), ('BTUE', 'Tuesday'), ('CWED', 'Wednesday'), ('DTHU', 'Thursday'), ('EFRI', 'Friday')], default='NOD', max_length=4),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
