# Generated by Django 2.1.4 on 2019-01-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0007_auto_20190110_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceccevent',
            name='breakfast',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ceccevent',
            name='lunch',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ceccevent',
            name='snack',
            field=models.TextField(max_length=100),
        ),
    ]
