# Generated by Django 2.1.4 on 2019-01-13 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0008_auto_20190112_1140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ceccevent',
            new_name='Ceccmenu',
        ),
    ]
