# Generated by Django 2.1.4 on 2019-01-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0009_auto_20190113_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeccEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('dayno', models.IntegerField(default=1)),
                ('weekday', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], default='NOD', max_length=3)),
                ('event', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='ceccmenu',
            name='breakfast',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ceccmenu',
            name='lunch',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ceccmenu',
            name='snack',
            field=models.TextField(max_length=500),
        ),
    ]
