# Generated by Django 2.1.4 on 2019-01-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0010_auto_20190114_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceccevent',
            name='month',
            field=models.IntegerField(default=1),
        ),
    ]
