# Generated by Django 2.1.4 on 2019-01-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0011_auto_20190115_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceccmenu',
            name='season',
            field=models.CharField(choices=[('ASPR', 'Spring'), ('BSSM', 'Spring/Summer'), ('CSUM', 'Summer'), ('DAUW', 'Autumn/Winter')], default='ASPR', max_length=4),
        ),
    ]
