# Generated by Django 2.1.4 on 2019-01-27 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0012_ceccmenu_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='oscarballot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bestpicture', models.CharField(default='NA', max_length=100)),
                ('actor', models.CharField(default='NA', max_length=100)),
                ('actress', models.CharField(default='NA', max_length=100)),
                ('supactor', models.CharField(default='NA', max_length=100)),
                ('supactress', models.CharField(default='NA', max_length=100)),
                ('animatedfeature', models.CharField(default='NA', max_length=100)),
                ('cinematography', models.CharField(default='NA', max_length=100)),
                ('costume', models.CharField(default='NA', max_length=100)),
                ('directing', models.CharField(default='NA', max_length=100)),
                ('documentary', models.CharField(default='NA', max_length=100)),
                ('docshort', models.CharField(default='NA', max_length=100)),
                ('fediting', models.CharField(default='NA', max_length=100)),
                ('foreign', models.CharField(default='NA', max_length=100)),
                ('makeupandh', models.CharField(default='NA', max_length=100)),
                ('mscore', models.CharField(default='NA', max_length=100)),
                ('msong', models.CharField(default='NA', max_length=100)),
                ('prodesign', models.CharField(default='NA', max_length=100)),
                ('animatedshort', models.CharField(default='NA', max_length=100)),
                ('shortfilm', models.CharField(default='NA', max_length=100)),
                ('sediting', models.CharField(default='NA', max_length=100)),
                ('smixing', models.CharField(default='NA', max_length=100)),
                ('visualfx', models.CharField(default='NA', max_length=100)),
                ('writingad', models.CharField(default='NA', max_length=100)),
                ('writingor', models.CharField(default='NA', max_length=100)),
                ('skore', models.IntegerField(default=0)),
                ('vwidth', models.IntegerField(default=0)),
                ('kulr', models.CharField(default='#fc0', max_length=20)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestpicture', models.CharField(default='NA', max_length=100)),
                ('actor', models.CharField(default='NA', max_length=100)),
                ('actress', models.CharField(default='NA', max_length=100)),
                ('supactor', models.CharField(default='NA', max_length=100)),
                ('supactress', models.CharField(default='NA', max_length=100)),
                ('animatedfeature', models.CharField(default='NA', max_length=100)),
                ('cinematography', models.CharField(default='NA', max_length=100)),
                ('costume', models.CharField(default='NA', max_length=100)),
                ('directing', models.CharField(default='NA', max_length=100)),
                ('documentary', models.CharField(default='NA', max_length=100)),
                ('docshort', models.CharField(default='NA', max_length=100)),
                ('fediting', models.CharField(default='NA', max_length=100)),
                ('foreign', models.CharField(default='NA', max_length=100)),
                ('makeupandh', models.CharField(default='NA', max_length=100)),
                ('mscore', models.CharField(default='NA', max_length=100)),
                ('msong', models.CharField(default='NA', max_length=100)),
                ('prodesign', models.CharField(default='NA', max_length=100)),
                ('animatedshort', models.CharField(default='NA', max_length=100)),
                ('shortfilm', models.CharField(default='NA', max_length=100)),
                ('sediting', models.CharField(default='NA', max_length=100)),
                ('smixing', models.CharField(default='NA', max_length=100)),
                ('visualfx', models.CharField(default='NA', max_length=100)),
                ('writingad', models.CharField(default='NA', max_length=100)),
                ('writingor', models.CharField(default='NA', max_length=100)),
            ],
        ),
    ]
