# Generated by Django 2.1.4 on 2019-01-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0013_oscarballot_winners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oscarballot',
            name='actor',
            field=models.CharField(choices=[('Timothee Chalamet', 'Timothee Chalamet (Call Me by Your Name)'), ('Daniel Day-Lewis', 'Daniel Day-Lewis (Phantom Thread)'), ('Daniel Kaluuya', 'Daniel Kaluuya (Get Out)'), ('Gary Oldman', 'Gary Oldman (Darkest Hour)'), ('Denzel Washington', 'Denzel Washington (Roman J. Israel, Esq.)')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='actress',
            field=models.CharField(choices=[('Sally Hawkins', 'Sally Hawkins (The Shape of Water)'), ('Frances McDormand', 'Frances McDormand (Three Billboards Outside Ebbing Missouri)'), ('Margot Robbie', 'Margot Robbie (I, Tonya)'), ('Saoirse Ronan', 'Saoirse Ronan (Lady Bird)'), ('Meryl Streep', 'Meryl Streep (The Post)')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='animatedfeature',
            field=models.CharField(choices=[('Boss Baby', 'Boss Baby'), ('The Breadwinner', 'The Breadwinner'), ('Coco', 'Coco'), ('Ferdinand', 'Ferdinand'), ('Loving Vincent', 'Loving Vincent')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='animatedshort',
            field=models.CharField(choices=[('Dear Basketball', 'Dear Basketball'), ('Garden Party', 'Garden Party'), ('Lou', 'Lou'), ('Negative Space', 'Negative Space'), ('Revolting Rhymes', 'Revolting Rhymes')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='bestpicture',
            field=models.CharField(choices=[('Call Me by Your Name', 'Call Me by Your Name'), ('Darkest Hour', 'Darkest Hour'), ('Dunkirk', 'Dunkirk'), ('Get Out', 'Get Out'), ('Lady Bird', 'Lady Bird'), ('Phantom Thread', 'Phantom Thread'), ('The Post', 'The Post'), ('The Shape of Water', 'The Shape of Water'), ('Three Billboards Outside Ebbing Missouri', 'Three Billboards Outside Ebbing Missouri')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='cinematography',
            field=models.CharField(choices=[('Blade Runner 2049', 'Blade Runner 2049'), ('Darkest Hour', 'Darkest Hour'), ('Dunkirk', 'Dunkirk'), ('Mudbound', 'Mudbound'), ('The Shape of Water', 'The Shape of Water')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='costume',
            field=models.CharField(choices=[('Beauty and the Beast', 'Beauty and the Beast'), ('Darkest Hour', 'Darkest Hour'), ('Phantom Thread', 'Phantom Thread'), ('The Shape of Water', 'The Shape of Water'), ('Victoria & Abdul', 'Victoria & Abdul')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='directing',
            field=models.CharField(choices=[('Christopher Nolan', 'Christopher Nolan (Dunkirk)'), ('Jordan Peele', 'Jordan Peele (Get Out)'), ('Greta Gerwig', 'Greta Gerwig (Lady Bird)'), ('Paul Thomas Anderson', 'Paul Thomas Anderson (Phantom Thread)'), ('Guillermo del Toro', 'Guillermo del Toro (The Shape of Water)')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='docshort',
            field=models.CharField(choices=[('Edith+Eddie', 'Edith+Eddie'), ('Heaven Is a Traffic Jam on the 405', 'Heaven Is a Traffic Jam on the 405'), ('Heroin(e)', 'Heroin(e)'), ('Knife Skills', 'Knife Skills'), ('Traffic Stop', 'Traffic Stop')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='documentary',
            field=models.CharField(choices=[('Abacus: Small Enough to Jail', 'Abacus: Small Enough to Jail'), ('Faces Places', 'Faces Places'), ('Icarus', 'Icarus'), ('Last Men in Aleppo', 'Last Men in Aleppo'), ('Strong Island', 'Strong Island')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='fediting',
            field=models.CharField(choices=[('Baby Driver', 'Baby Driver'), ('Dunkirk', 'Dunkirk'), ('I, Tonya', 'I, Tonya'), ('The Shape of Water', 'The Shape of Water'), ('Three Billboards Outside Ebbing Missouri', 'Three Billboards Outside Ebbing Missouri')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='foreign',
            field=models.CharField(choices=[('A Fantastic Woman', 'A Fantastic Woman'), ('The Insult', 'The Insult'), ('Loveless', 'Loveless'), ('On Body and Soul', 'On Body and Soul'), ('The Square', 'The Square')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='makeupandh',
            field=models.CharField(choices=[('Darkest Hour', 'Darkest Hour'), ('Victoria & Abdul', 'Victoria & Abdul'), ('Wonder', 'Wonder')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='mscore',
            field=models.CharField(choices=[('Dunkirk', 'Dunkirk'), ('Phantom Thread', 'Phantom Thread'), ('The Shape of Water', 'The Shape of Water'), ('Star Wars: The Last Jedi', 'Star Wars: The Last Jedi'), ('Three Billboards Outside Ebbing Missouri', 'Three Billboards Outside Ebbing Missouri')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='msong',
            field=models.CharField(choices=[('Mighty River', 'Mighty River (Mudbound)'), ('Mystery of Love', 'Mystery Of Love (Call Me by Your Name)'), ('Remember Me', 'Remember Me (Coco)'), ('Stand Up For Something', 'Stand Up For Something (Marshall)'), ('This is Me', 'This Is Me (The Greatest Showman)')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='name',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='prodesign',
            field=models.CharField(choices=[('Beauty and the Beast', 'Beauty and the Beast'), ('Blade Runner 2049', 'Blade Runner 2049'), ('Darkest Hour', 'Darkest Hour'), ('Dunkirk', 'Dunkirk'), ('The Shape of Water', 'The Shape of Water')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='sediting',
            field=models.CharField(choices=[('Baby Driver', 'Baby Driver'), ('Blade Runner 2049', 'Blade Runner 2049'), ('Dunkirk', 'Dunkirk'), ('The Shape of Water', 'The Shape of Water'), ('Star Wars: The Last Jedi', 'Star Wars: The Last Jedi')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='shortfilm',
            field=models.CharField(choices=[('DeKalb Elementary', 'DeKalb Elementary'), ('The Eleven OClock', 'The Eleven OClock'), ('My Nephew Emmett', 'My Nephew Emmett'), ('The Silent Child', 'The Silent Child'), ('Watu Wote/All of Us', 'Watu Wote/All of Us')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='smixing',
            field=models.CharField(choices=[('Baby Driver', 'Baby Driver'), ('Blade Runner 2049', 'Blade Runner 2049'), ('Dunkirk', 'Dunkirk'), ('The Shape of Water', 'The Shape of Water'), ('Star Wars: The Last Jedi', 'Star Wars: The Last Jedi')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='supactor',
            field=models.CharField(choices=[('Willem Dafoe', 'Willem Dafoe (The Florida Project)'), ('Woody Harrelson', 'Woody Harrelson (Three Billboards Outside Ebbing Missouri)'), ('Richard Jenkins', 'Richard Jenkins (The Shape of Water)'), ('Christopher Plummer', 'Christopher Plummer (All the Money in the World)'), ('Sam Rockwell', 'Sam Rockwell (Three Billboards Outside Ebbing Missouri)')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='supactress',
            field=models.CharField(choices=[('Mary J. Blige', 'Mary J. Blige (Mudbound)'), ('Allison Janney', 'Allison Janney (I, Tonya)'), ('Lesley Manville', 'Lesley Manville (Phantom Thread)'), ('Laurie Metcalf', 'Laurie Metcalf (Lady Bird)'), ('Octavia Spencer', 'Octavia Spencer (The Shape of Water)')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='visualfx',
            field=models.CharField(choices=[('Blade Runner 2049', 'Blade Runner 2049'), ('Gaurdians of the Galaxy Vol. 2', 'Guardians of the Galaxy Vol. 2'), ('Kong: Skull Island', 'Kong: Skull Island'), ('Star Wars: The Last Jedi', 'Star Wars: The Last Jedi'), ('War for the Planet of the Apes', 'War for the Planet of the Apes')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='writingad',
            field=models.CharField(choices=[('Call Me by Your Name', 'Call Me by Your Name'), ('The Disaster Artist', 'The Disaster Artist'), ('Logan', 'Logan'), ('Mollys Game', 'Mollys Game'), ('Mudbound', 'Mudbound')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='writingor',
            field=models.CharField(choices=[('The Big Sick', 'The Big Sick'), ('Get Out', 'Get Out'), ('Lady Bird', 'Lady Bird'), ('The Shape of Water', 'The Shape of Water'), ('Three Billboards Outside Ebbing Missouri', 'Three Billboards Outside Ebbing Missouri')], default='NA', max_length=100),
        ),
    ]
