# Generated by Django 2.1.4 on 2019-01-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0015_auto_20190129_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oscarballot',
            name='actor',
            field=models.CharField(choices=[('Christian Bale, Vice', 'Christian Bale, Vice'), ('Bradley Cooper, A Star is Born', 'Bradley Cooper, A Star is Born'), ("Willem Dafoe, At Eternity's Gate", "Willem Dafoe, At Eternity's Gate"), ('Rami Malek, Bohemian Rhapsody', 'Rami Malek, Bohemian Rhapsody'), ('Viggo Mortensen, Green Book', 'Viggo Mortensen, Green Book')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='actress',
            field=models.CharField(choices=[('Yalitza Aparicio, Roma', 'Yalitza Aparicio, Roma'), ('Glenn Close, The Wife', 'Glenn Close, The Wife'), ('Olivia Colman, The Favourite', 'Olivia Colman, The Favourite'), ('Lady Gaga, A Star is Born', 'Lady Gaga, A Star is Born'), ('Melissa McCarthy, Can You Ever Forgive Me?', 'Melissa McCarthy, Can You Ever Forgive Me?')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='animatedfeature',
            field=models.CharField(choices=[('Incredibles 2', 'Incredibles 2'), ('Isle of Dogs', 'Isle of Dogs'), ('Mirai', 'Mirai'), ('Ralph Breaks the Internet', 'Ralph Breaks the Internet'), ('Spider-Man: Into the Spider-Verse', 'Spider-Man: Into the Spider-Verse')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='animatedshort',
            field=models.CharField(choices=[('Animal Behavior, Alison Snowden, David Fine', 'Animal Behavior, Alison Snowden, David Fine'), ('Bao, Domee Shi', 'Bao, Domee Shi'), ('Late Afternoon, Louise Bagnall', 'Late Afternoon, Louise Bagnall'), ('One Small Step, Andrew Chesworth, Bobby Pontillas', 'One Small Step, Andrew Chesworth, Bobby Pontillas'), ('Weekends, Trevor Jimenez', 'Weekends, Trevor Jimenez')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='bestpicture',
            field=models.CharField(choices=[('Black Panther', 'Black Panther'), ('BlacKkKlansman', 'BlacKkKlansman'), ('Bohemian Rhapsody', 'Bohemian Rhapsody'), ('The Favourite', 'The Favourite'), ('Green Book', 'Green Book'), ('Roma', 'Roma'), ('A Star is Born', 'A Star is Born'), ('Vice', 'Vice')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='cinematography',
            field=models.CharField(choices=[('Cold War (Poland)', 'Cold War (Poland)'), ('The Favourite', 'The Favourite'), ('Never Look Away (Germany)', 'Never Look Away (Germany)'), ('Roma', 'Roma'), ('A Star is Born', 'A Star is Born')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='costume',
            field=models.CharField(choices=[('The Ballad of Buster Scruggs', 'The Ballad of Buster Scruggs'), ('Black Panther', 'Black Panther'), ('The Favourite', 'The Favourite'), ('Mary Poppins Returns', 'Mary Poppins Returns'), ('Mary Queen of Scots', 'Mary Queen of Scots')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='directing',
            field=models.CharField(choices=[('Spike Lee, BlacKkKlansman', 'Spike Lee, BlacKkKlansman'), ('Pawel Pawlikowski, Cold War', 'Pawel Pawlikowski, Cold War'), ('Yorgos Lanthimos, The Favourite', 'Yorgos Lanthimos, The Favourite'), ('Alfonso Cuaron, Roma', 'Alfonso Cuaron, Roma'), ('Adam McKay, Vice', 'Adam McKay, Vice')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='docshort',
            field=models.CharField(choices=[('Black Sheep', 'Black Sheep'), ('End Game', 'End Game'), ('Lifeboat', 'Lifeboat'), ('A Night at the Garden', 'A Night at the Garden'), ('Period. End of Sentence.', 'Period. End of Sentence.')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='documentary',
            field=models.CharField(choices=[('Free Solo', 'Free Solo'), ('Hale County This Morning, This Evening', 'Hale County This Morning, This Evening'), ('Mind the Gap', 'Mind the Gap'), ('Of Fathers and Sons', 'Of Fathers and Sons'), ('RBG', 'RBG')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='fediting',
            field=models.CharField(choices=[('BlacKkKlansman', 'BlacKkKlansman'), ('Bohemian Rhapsody', 'Bohemian Rhapsody'), ('Green Book', 'Green Book'), ('The Favourite', 'The Favourite'), ('Vice', 'Vice')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='foreign',
            field=models.CharField(choices=[('Capernaum (Lebanon)', 'Capernaum (Lebanon)'), ('Cold War (Poland)', 'Cold War (Poland)'), ('Never Look Away (Germany)', 'Never Look Away (Germany)'), ('Roma', 'Roma'), ('Shoplifters (Japan)', 'Shoplifters (Japan)')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='makeupandh',
            field=models.CharField(choices=[('Border', 'Border'), ('Mary Queen of Scots', 'Mary Queen of Scots'), ('Vice', 'Vice')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='mscore',
            field=models.CharField(choices=[('BlacKkKlansman', 'BlacKkKlansman'), ('Black Panther', 'Black Panther'), ('If Beale Street Could Talk', 'If Beale Street Could Talk'), ('Isle of Dogs', 'Isle of Dogs'), ('Mary Poppins Returns', 'Mary Poppins Returns')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='msong',
            field=models.CharField(choices=[('All The Stars (Black Panther)', 'All The Stars (Black Panther)'), ("I'll Fight (RBG)", "I'll Fight (RBG)"), ('The Place Where Lost Things Go (Mary Poppins Returns)', 'The Place Where Lost Things Go (Mary Poppins Returns)'), ('Shallow (A Star is Born)', 'Shallow (A Star is Born)'), ('When A Cowboy Trades His Spurs For Wings (The Ballad of Buster Scruggs)', 'When A Cowboy Trades His Spurs For Wings (The Ballad of Buster Scruggs)')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='prodesign',
            field=models.CharField(choices=[('Black Panther', 'Black Panther'), ('First Man', 'First Man'), ('The Favourite', 'The Favourite'), ('Mary Poppins Returns', 'Mary Poppins Returns'), ('Roma', 'Roma (Mexico)')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='sediting',
            field=models.CharField(choices=[('Black Panther', 'Black Panther'), ('Bohemian Rhapsody', 'Bohemian Rhapsody'), ('First Man', 'First Man'), ('A Quiet Place', 'A Quiet Place'), ('Roma', 'Roma')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='shortfilm',
            field=models.CharField(choices=[('Detainment', 'Detainment'), ('Fauve', 'Fauve'), ('Marguerite', 'Marguerite'), ('Mother', 'Mother'), ('Skin', 'Skin')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='smixing',
            field=models.CharField(choices=[('Black Panther', 'Black Panther'), ('Bohemian Rhapsody', 'Bohemian Rhapsody'), ('First Man', 'First Man'), ('Roma', 'Roma'), ('A Star is Born', 'A Star is Born')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='supactor',
            field=models.CharField(choices=[('Mahershala Ali, Green Book', 'Mahershala Ali, Green Book'), ('Adam Driver, BlacKkKlansman', 'Adam Driver, BlacKkKlansman'), ('Sam Elliott, A Star is Born', 'Sam Elliott, A Star is Born'), ('Richard E. Grant, Can You Ever Forgive Me?', 'Richard E. Grant, Can You Ever Forgive Me?'), ('Spider-Man: Into the Spider-Verse', 'Spider-Man: Into the Spider-Verse')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='supactress',
            field=models.CharField(choices=[('Amy Adams, Vice', 'Amy Adams, Vice'), ('Marina de Tavira, Roma', 'Marina de Tavira, Roma'), ('Regina King, If Beale Street Could Talk', 'Regina King, If Beale Street Could Talk'), ('Emma Stone, The Favourite', 'Emma Stone, The Favourite'), ('Rachel Weisz, The Favourite', 'Rachel Weisz, The Favourite')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='visualfx',
            field=models.CharField(choices=[('Avengers: Infinity War', 'Avengers: Infinity War'), ('Christopher Robin', 'Christopher Robin'), ('First Man', 'First Man'), ('Ready Player One', 'Ready Player One'), ('Solo: A Star Wars Story', 'Solo: A Star Wars Story')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='writingad',
            field=models.CharField(choices=[('The Ballad of Buster Scruggs', 'The Ballad of Buster Scruggs'), ('BlacKkKlansman', 'BlacKkKlansman'), ('Can You Ever Forgive Me?', 'Can You Ever Forgive Me?'), ('If Beale Street Could Talk', 'If Beale Street Could Talk'), ('A Star is Born', 'A Star is Born')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='writingor',
            field=models.CharField(choices=[('The Favourite', 'The Favourite'), ('First Reformed', 'First Reformed'), ('Green Book', 'Green Book'), ('Roma', 'Roma'), ('Vice', 'Vice')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='actor',
            field=models.CharField(choices=[('Christian Bale, Vice', 'Christian Bale, Vice'), ('Bradley Cooper, A Star is Born', 'Bradley Cooper, A Star is Born'), ("Willem Dafoe, At Eternity's Gate", "Willem Dafoe, At Eternity's Gate"), ('Rami Malek, Bohemian Rhapsody', 'Rami Malek, Bohemian Rhapsody'), ('Viggo Mortensen, Green Book', 'Viggo Mortensen, Green Book')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='actress',
            field=models.CharField(choices=[('Yalitza Aparicio, Roma', 'Yalitza Aparicio, Roma'), ('Glenn Close, The Wife', 'Glenn Close, The Wife'), ('Olivia Colman, The Favourite', 'Olivia Colman, The Favourite'), ('Lady Gaga, A Star is Born', 'Lady Gaga, A Star is Born'), ('Melissa McCarthy, Can You Ever Forgive Me?', 'Melissa McCarthy, Can You Ever Forgive Me?')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='animatedfeature',
            field=models.CharField(choices=[('Incredibles 2', 'Incredibles 2'), ('Isle of Dogs', 'Isle of Dogs'), ('Mirai', 'Mirai'), ('Ralph Breaks the Internet', 'Ralph Breaks the Internet'), ('Spider-Man: Into the Spider-Verse', 'Spider-Man: Into the Spider-Verse')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='animatedshort',
            field=models.CharField(choices=[('Animal Behavior, Alison Snowden, David Fine', 'Animal Behavior, Alison Snowden, David Fine'), ('Bao, Domee Shi', 'Bao, Domee Shi'), ('Late Afternoon, Louise Bagnall', 'Late Afternoon, Louise Bagnall'), ('One Small Step, Andrew Chesworth, Bobby Pontillas', 'One Small Step, Andrew Chesworth, Bobby Pontillas'), ('Weekends, Trevor Jimenez', 'Weekends, Trevor Jimenez')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='bestpicture',
            field=models.CharField(choices=[('Black Panther', 'Black Panther'), ('BlacKkKlansman', 'BlacKkKlansman'), ('Bohemian Rhapsody', 'Bohemian Rhapsody'), ('The Favourite', 'The Favourite'), ('Green Book', 'Green Book'), ('Roma', 'Roma'), ('A Star is Born', 'A Star is Born'), ('Vice', 'Vice')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='cinematography',
            field=models.CharField(choices=[('Cold War (Poland)', 'Cold War (Poland)'), ('The Favourite', 'The Favourite'), ('Never Look Away (Germany)', 'Never Look Away (Germany)'), ('Roma', 'Roma'), ('A Star is Born', 'A Star is Born')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='costume',
            field=models.CharField(choices=[('The Ballad of Buster Scruggs', 'The Ballad of Buster Scruggs'), ('Black Panther', 'Black Panther'), ('The Favourite', 'The Favourite'), ('Mary Poppins Returns', 'Mary Poppins Returns'), ('Mary Queen of Scots', 'Mary Queen of Scots')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='directing',
            field=models.CharField(choices=[('Spike Lee, BlacKkKlansman', 'Spike Lee, BlacKkKlansman'), ('Pawel Pawlikowski, Cold War', 'Pawel Pawlikowski, Cold War'), ('Yorgos Lanthimos, The Favourite', 'Yorgos Lanthimos, The Favourite'), ('Alfonso Cuaron, Roma', 'Alfonso Cuaron, Roma'), ('Adam McKay, Vice', 'Adam McKay, Vice')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='docshort',
            field=models.CharField(choices=[('Black Sheep', 'Black Sheep'), ('End Game', 'End Game'), ('Lifeboat', 'Lifeboat'), ('A Night at the Garden', 'A Night at the Garden'), ('Period. End of Sentence.', 'Period. End of Sentence.')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='documentary',
            field=models.CharField(choices=[('Free Solo', 'Free Solo'), ('Hale County This Morning, This Evening', 'Hale County This Morning, This Evening'), ('Mind the Gap', 'Mind the Gap'), ('Of Fathers and Sons', 'Of Fathers and Sons'), ('RBG', 'RBG')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='fediting',
            field=models.CharField(choices=[('BlacKkKlansman', 'BlacKkKlansman'), ('Bohemian Rhapsody', 'Bohemian Rhapsody'), ('Green Book', 'Green Book'), ('The Favourite', 'The Favourite'), ('Vice', 'Vice')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='foreign',
            field=models.CharField(choices=[('Capernaum (Lebanon)', 'Capernaum (Lebanon)'), ('Cold War (Poland)', 'Cold War (Poland)'), ('Never Look Away (Germany)', 'Never Look Away (Germany)'), ('Roma', 'Roma'), ('Shoplifters (Japan)', 'Shoplifters (Japan)')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='makeupandh',
            field=models.CharField(choices=[('Border', 'Border'), ('Mary Queen of Scots', 'Mary Queen of Scots'), ('Vice', 'Vice')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='mscore',
            field=models.CharField(choices=[('BlacKkKlansman', 'BlacKkKlansman'), ('Black Panther', 'Black Panther'), ('If Beale Street Could Talk', 'If Beale Street Could Talk'), ('Isle of Dogs', 'Isle of Dogs'), ('Mary Poppins Returns', 'Mary Poppins Returns')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='msong',
            field=models.CharField(choices=[('All The Stars (Black Panther)', 'All The Stars (Black Panther)'), ("I'll Fight (RBG)", "I'll Fight (RBG)"), ('The Place Where Lost Things Go (Mary Poppins Returns)', 'The Place Where Lost Things Go (Mary Poppins Returns)'), ('Shallow (A Star is Born)', 'Shallow (A Star is Born)'), ('When A Cowboy Trades His Spurs For Wings (The Ballad of Buster Scruggs)', 'When A Cowboy Trades His Spurs For Wings (The Ballad of Buster Scruggs)')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='prodesign',
            field=models.CharField(choices=[('Black Panther', 'Black Panther'), ('First Man', 'First Man'), ('The Favourite', 'The Favourite'), ('Mary Poppins Returns', 'Mary Poppins Returns'), ('Roma', 'Roma (Mexico)')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='sediting',
            field=models.CharField(choices=[('Black Panther', 'Black Panther'), ('Bohemian Rhapsody', 'Bohemian Rhapsody'), ('First Man', 'First Man'), ('A Quiet Place', 'A Quiet Place'), ('Roma', 'Roma')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='shortfilm',
            field=models.CharField(choices=[('Detainment', 'Detainment'), ('Fauve', 'Fauve'), ('Marguerite', 'Marguerite'), ('Mother', 'Mother'), ('Skin', 'Skin')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='smixing',
            field=models.CharField(choices=[('Black Panther', 'Black Panther'), ('Bohemian Rhapsody', 'Bohemian Rhapsody'), ('First Man', 'First Man'), ('Roma', 'Roma'), ('A Star is Born', 'A Star is Born')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='supactor',
            field=models.CharField(choices=[('Mahershala Ali, Green Book', 'Mahershala Ali, Green Book'), ('Adam Driver, BlacKkKlansman', 'Adam Driver, BlacKkKlansman'), ('Sam Elliott, A Star is Born', 'Sam Elliott, A Star is Born'), ('Richard E. Grant, Can You Ever Forgive Me?', 'Richard E. Grant, Can You Ever Forgive Me?'), ('Spider-Man: Into the Spider-Verse', 'Spider-Man: Into the Spider-Verse')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='supactress',
            field=models.CharField(choices=[('Amy Adams, Vice', 'Amy Adams, Vice'), ('Marina de Tavira, Roma', 'Marina de Tavira, Roma'), ('Regina King, If Beale Street Could Talk', 'Regina King, If Beale Street Could Talk'), ('Emma Stone, The Favourite', 'Emma Stone, The Favourite'), ('Rachel Weisz, The Favourite', 'Rachel Weisz, The Favourite')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='visualfx',
            field=models.CharField(choices=[('Avengers: Infinity War', 'Avengers: Infinity War'), ('Christopher Robin', 'Christopher Robin'), ('First Man', 'First Man'), ('Ready Player One', 'Ready Player One'), ('Solo: A Star Wars Story', 'Solo: A Star Wars Story')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='writingad',
            field=models.CharField(choices=[('The Ballad of Buster Scruggs', 'The Ballad of Buster Scruggs'), ('BlacKkKlansman', 'BlacKkKlansman'), ('Can You Ever Forgive Me?', 'Can You Ever Forgive Me?'), ('If Beale Street Could Talk', 'If Beale Street Could Talk'), ('A Star is Born', 'A Star is Born')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='writingor',
            field=models.CharField(choices=[('The Favourite', 'The Favourite'), ('First Reformed', 'First Reformed'), ('Green Book', 'Green Book'), ('Roma', 'Roma'), ('Vice', 'Vice')], default='NA', max_length=100),
        ),
    ]
