# Generated by Django 2.1.4 on 2019-01-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0016_auto_20190130_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oscarballot',
            name='animatedshort',
            field=models.CharField(choices=[('Animal Behavior', 'Animal Behavior'), ('Bao', 'Bao'), ('Late Afternoon', 'Late Afternoon'), ('One Small Step', 'One Small Step'), ('Weekends', 'Weekends')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='cinematography',
            field=models.CharField(choices=[('Cold War', 'Cold War'), ('The Favourite', 'The Favourite'), ('Never Look Away', 'Never Look Away'), ('Roma', 'Roma'), ('A Star is Born', 'A Star is Born')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='foreign',
            field=models.CharField(choices=[('Capernaum (Lebanon)', 'Capernaum (Lebanon)'), ('Cold War', 'Cold War (Poland)'), ('Never Look Away', 'Never Look Away (Germany)'), ('Roma', 'Roma (Mexico)'), ('Shoplifters (Japan)', 'Shoplifters (Japan)')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='prodesign',
            field=models.CharField(choices=[('Black Panther', 'Black Panther'), ('First Man', 'First Man'), ('The Favourite', 'The Favourite'), ('Mary Poppins Returns', 'Mary Poppins Returns'), ('Roma', 'Roma')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='animatedshort',
            field=models.CharField(choices=[('Animal Behavior', 'Animal Behavior'), ('Bao', 'Bao'), ('Late Afternoon', 'Late Afternoon'), ('One Small Step', 'One Small Step'), ('Weekends', 'Weekends')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='cinematography',
            field=models.CharField(choices=[('Cold War', 'Cold War'), ('The Favourite', 'The Favourite'), ('Never Look Away', 'Never Look Away'), ('Roma', 'Roma'), ('A Star is Born', 'A Star is Born')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='foreign',
            field=models.CharField(choices=[('Capernaum (Lebanon)', 'Capernaum (Lebanon)'), ('Cold War', 'Cold War (Poland)'), ('Never Look Away', 'Never Look Away (Germany)'), ('Roma', 'Roma (Mexico)'), ('Shoplifters (Japan)', 'Shoplifters (Japan)')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='prodesign',
            field=models.CharField(choices=[('Black Panther', 'Black Panther'), ('First Man', 'First Man'), ('The Favourite', 'The Favourite'), ('Mary Poppins Returns', 'Mary Poppins Returns'), ('Roma', 'Roma')], default='NA', max_length=100),
        ),
    ]
