# Generated by Django 2.1.4 on 2019-01-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0017_auto_20190130_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oscarballot',
            name='supactor',
            field=models.CharField(choices=[('Mahershala Ali, Green Book', 'Mahershala Ali, Green Book'), ('Adam Driver, BlacKkKlansman', 'Adam Driver, BlacKkKlansman'), ('Sam Elliott, A Star is Born', 'Sam Elliott, A Star is Born'), ('Richard E. Grant, Can You Ever Forgive Me?', 'Richard E. Grant, Can You Ever Forgive Me?'), ('Sam Rockwell, Vice', 'Sam Rockwell, Vice')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='supactor',
            field=models.CharField(choices=[('Mahershala Ali, Green Book', 'Mahershala Ali, Green Book'), ('Adam Driver, BlacKkKlansman', 'Adam Driver, BlacKkKlansman'), ('Sam Elliott, A Star is Born', 'Sam Elliott, A Star is Born'), ('Richard E. Grant, Can You Ever Forgive Me?', 'Richard E. Grant, Can You Ever Forgive Me?'), ('Sam Rockwell, Vice', 'Sam Rockwell, Vice')], default='NA', max_length=100),
        ),
    ]
