# Generated by Django 2.1.4 on 2019-01-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0018_auto_20190130_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oscarballot',
            name='documentary',
            field=models.CharField(choices=[('Free Solo', 'Free Solo'), ('Hale County This Morning, This Evening', 'Hale County This Morning, This Evening'), ('Minding the Gap', 'Minding the Gap'), ('Of Fathers and Sons', 'Of Fathers and Sons'), ('RBG', 'RBG')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='documentary',
            field=models.CharField(choices=[('Free Solo', 'Free Solo'), ('Hale County This Morning, This Evening', 'Hale County This Morning, This Evening'), ('Minding the Gap', 'Minding the Gap'), ('Of Fathers and Sons', 'Of Fathers and Sons'), ('RBG', 'RBG')], default='NA', max_length=100),
        ),
    ]
