# Generated by Django 2.1.4 on 2019-02-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0019_auto_20190130_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='oscarballot',
            name='wwidth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='actor',
            field=models.CharField(choices=[('Christian Bale', 'Christian Bale'), ('Bradley Cooper', 'Bradley Cooper'), ('Willem Dafoe', 'Willem Dafoe'), ('Rami Malek', 'Rami Malek'), ('Viggo Mortensen', 'Viggo Mortensen')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='actress',
            field=models.CharField(choices=[('Yalitza Aparicio', 'Yalitza Aparicio'), ('Glenn Close', 'Glenn Close'), ('Olivia Colman', 'Olivia Colman'), ('Lady Gaga', 'Lady Gaga'), ('Melissa McCarthy', 'Melissa McCarthy')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='directing',
            field=models.CharField(choices=[('Spike Lee', 'Spike Lee'), ('Pawel Pawlikowski', 'Pawel Pawlikowski'), ('Yorgos Lanthimos', 'Yorgos Lanthimos'), ('Alfonso Cuaron', 'Alfonso Cuaron'), ('Adam McKay', 'Adam McKay')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='supactor',
            field=models.CharField(choices=[('Mahershala Ali', 'Mahershala Ali'), ('Adam Driver', 'Adam Driver'), ('Sam Elliott', 'Sam Elliott'), ('Richard E. Grant', 'Richard E. Grant'), ('Sam Rockwell', 'Sam Rockwell')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='oscarballot',
            name='supactress',
            field=models.CharField(choices=[('Amy Adams', 'Amy Adams'), ('Marina de Tavira', 'Marina de Tavira'), ('Regina King', 'Regina King'), ('Emma Stone', 'Emma Stone'), ('Rachel Weisz', 'Rachel Weisz')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='actor',
            field=models.CharField(choices=[('Christian Bale', 'Christian Bale'), ('Bradley Cooper', 'Bradley Cooper'), ('Willem Dafoe', 'Willem Dafoe'), ('Rami Malek', 'Rami Malek'), ('Viggo Mortensen', 'Viggo Mortensen')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='actress',
            field=models.CharField(choices=[('Yalitza Aparicio', 'Yalitza Aparicio'), ('Glenn Close', 'Glenn Close'), ('Olivia Colman', 'Olivia Colman'), ('Lady Gaga', 'Lady Gaga'), ('Melissa McCarthy', 'Melissa McCarthy')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='directing',
            field=models.CharField(choices=[('Spike Lee', 'Spike Lee'), ('Pawel Pawlikowski', 'Pawel Pawlikowski'), ('Yorgos Lanthimos', 'Yorgos Lanthimos'), ('Alfonso Cuaron', 'Alfonso Cuaron'), ('Adam McKay', 'Adam McKay')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='supactor',
            field=models.CharField(choices=[('Mahershala Ali', 'Mahershala Ali'), ('Adam Driver', 'Adam Driver'), ('Sam Elliott', 'Sam Elliott'), ('Richard E. Grant', 'Richard E. Grant'), ('Sam Rockwell', 'Sam Rockwell')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='supactress',
            field=models.CharField(choices=[('Amy Adams', 'Amy Adams'), ('Marina de Tavira', 'Marina de Tavira'), ('Regina King', 'Regina King'), ('Emma Stone', 'Emma Stone'), ('Rachel Weisz', 'Rachel Weisz')], default='NA', max_length=100),
        ),
    ]
