# Generated by Django 2.1.4 on 2019-02-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0020_auto_20190204_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winners',
            name='actor',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Christian Bale', 'Christian Bale'), ('Bradley Cooper', 'Bradley Cooper'), ('Willem Dafoe', 'Willem Dafoe'), ('Rami Malek', 'Rami Malek'), ('Viggo Mortensen', 'Viggo Mortensen')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='actress',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Yalitza Aparicio', 'Yalitza Aparicio'), ('Glenn Close', 'Glenn Close'), ('Olivia Colman', 'Olivia Colman'), ('Lady Gaga', 'Lady Gaga'), ('Melissa McCarthy', 'Melissa McCarthy')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='animatedfeature',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Incredibles 2', 'Incredibles 2'), ('Isle of Dogs', 'Isle of Dogs'), ('Mirai', 'Mirai'), ('Ralph Breaks the Internet', 'Ralph Breaks the Internet'), ('Spider-Man: Into the Spider-Verse', 'Spider-Man: Into the Spider-Verse')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='animatedshort',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Animal Behavior', 'Animal Behavior'), ('Bao', 'Bao'), ('Late Afternoon', 'Late Afternoon'), ('One Small Step', 'One Small Step'), ('Weekends', 'Weekends')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='bestpicture',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Black Panther', 'Black Panther'), ('BlacKkKlansman', 'BlacKkKlansman'), ('Bohemian Rhapsody', 'Bohemian Rhapsody'), ('The Favourite', 'The Favourite'), ('Green Book', 'Green Book'), ('Roma', 'Roma'), ('A Star is Born', 'A Star is Born'), ('Vice', 'Vice')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='cinematography',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Cold War', 'Cold War'), ('The Favourite', 'The Favourite'), ('Never Look Away', 'Never Look Away'), ('Roma', 'Roma'), ('A Star is Born', 'A Star is Born')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='costume',
            field=models.CharField(choices=[('TBD', 'TBD'), ('The Ballad of Buster Scruggs', 'The Ballad of Buster Scruggs'), ('Black Panther', 'Black Panther'), ('The Favourite', 'The Favourite'), ('Mary Poppins Returns', 'Mary Poppins Returns'), ('Mary Queen of Scots', 'Mary Queen of Scots')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='directing',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Spike Lee', 'Spike Lee'), ('Pawel Pawlikowski', 'Pawel Pawlikowski'), ('Yorgos Lanthimos', 'Yorgos Lanthimos'), ('Alfonso Cuaron', 'Alfonso Cuaron'), ('Adam McKay', 'Adam McKay')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='docshort',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Black Sheep', 'Black Sheep'), ('End Game', 'End Game'), ('Lifeboat', 'Lifeboat'), ('A Night at the Garden', 'A Night at the Garden'), ('Period. End of Sentence.', 'Period. End of Sentence.')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='documentary',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Free Solo', 'Free Solo'), ('Hale County This Morning, This Evening', 'Hale County This Morning, This Evening'), ('Minding the Gap', 'Minding the Gap'), ('Of Fathers and Sons', 'Of Fathers and Sons'), ('RBG', 'RBG')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='fediting',
            field=models.CharField(choices=[('TBD', 'TBD'), ('BlacKkKlansman', 'BlacKkKlansman'), ('Bohemian Rhapsody', 'Bohemian Rhapsody'), ('Green Book', 'Green Book'), ('The Favourite', 'The Favourite'), ('Vice', 'Vice')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='foreign',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Capernaum (Lebanon)', 'Capernaum (Lebanon)'), ('Cold War', 'Cold War (Poland)'), ('Never Look Away', 'Never Look Away (Germany)'), ('Roma', 'Roma (Mexico)'), ('Shoplifters (Japan)', 'Shoplifters (Japan)')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='makeupandh',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Border', 'Border'), ('Mary Queen of Scots', 'Mary Queen of Scots'), ('Vice', 'Vice')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='mscore',
            field=models.CharField(choices=[('TBD', 'TBD'), ('BlacKkKlansman', 'BlacKkKlansman'), ('Black Panther', 'Black Panther'), ('If Beale Street Could Talk', 'If Beale Street Could Talk'), ('Isle of Dogs', 'Isle of Dogs'), ('Mary Poppins Returns', 'Mary Poppins Returns')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='msong',
            field=models.CharField(choices=[('TBD', 'TBD'), ('All The Stars (Black Panther)', 'All The Stars (Black Panther)'), ("I'll Fight (RBG)", "I'll Fight (RBG)"), ('The Place Where Lost Things Go (Mary Poppins Returns)', 'The Place Where Lost Things Go (Mary Poppins Returns)'), ('Shallow (A Star is Born)', 'Shallow (A Star is Born)'), ('When A Cowboy Trades His Spurs For Wings (The Ballad of Buster Scruggs)', 'When A Cowboy Trades His Spurs For Wings (The Ballad of Buster Scruggs)')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='prodesign',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Black Panther', 'Black Panther'), ('First Man', 'First Man'), ('The Favourite', 'The Favourite'), ('Mary Poppins Returns', 'Mary Poppins Returns'), ('Roma', 'Roma')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='sediting',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Black Panther', 'Black Panther'), ('Bohemian Rhapsody', 'Bohemian Rhapsody'), ('First Man', 'First Man'), ('A Quiet Place', 'A Quiet Place'), ('Roma', 'Roma')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='shortfilm',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Detainment', 'Detainment'), ('Fauve', 'Fauve'), ('Marguerite', 'Marguerite'), ('Mother', 'Mother'), ('Skin', 'Skin')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='smixing',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Black Panther', 'Black Panther'), ('Bohemian Rhapsody', 'Bohemian Rhapsody'), ('First Man', 'First Man'), ('Roma', 'Roma'), ('A Star is Born', 'A Star is Born')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='supactor',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Mahershala Ali', 'Mahershala Ali'), ('Adam Driver', 'Adam Driver'), ('Sam Elliott', 'Sam Elliott'), ('Richard E. Grant', 'Richard E. Grant'), ('Sam Rockwell', 'Sam Rockwell')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='supactress',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Amy Adams', 'Amy Adams'), ('Marina de Tavira', 'Marina de Tavira'), ('Regina King', 'Regina King'), ('Emma Stone', 'Emma Stone'), ('Rachel Weisz', 'Rachel Weisz')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='visualfx',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Avengers: Infinity War', 'Avengers: Infinity War'), ('Christopher Robin', 'Christopher Robin'), ('First Man', 'First Man'), ('Ready Player One', 'Ready Player One'), ('Solo: A Star Wars Story', 'Solo: A Star Wars Story')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='writingad',
            field=models.CharField(choices=[('TBD', 'TBD'), ('The Ballad of Buster Scruggs', 'The Ballad of Buster Scruggs'), ('BlacKkKlansman', 'BlacKkKlansman'), ('Can You Ever Forgive Me?', 'Can You Ever Forgive Me?'), ('If Beale Street Could Talk', 'If Beale Street Could Talk'), ('A Star is Born', 'A Star is Born')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='winners',
            name='writingor',
            field=models.CharField(choices=[('TBD', 'TBD'), ('The Favourite', 'The Favourite'), ('First Reformed', 'First Reformed'), ('Green Book', 'Green Book'), ('Roma', 'Roma'), ('Vice', 'Vice')], default='NA', max_length=100),
        ),
    ]
