# Generated by Django 2.1.4 on 2019-03-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0022_umslballot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oscarballot',
            name='wwidth',
        ),
        migrations.AddField(
            model_name='oscarballot',
            name='place',
            field=models.IntegerField(default=1),
        ),
    ]
