# Generated by Django 2.1.4 on 2019-03-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0023_auto_20190302_0835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='oscarballot',
        ),
        migrations.DeleteModel(
            name='umslballot',
        ),
        migrations.DeleteModel(
            name='Winners',
        ),
    ]
