# Generated by Django 2.1.4 on 2020-08-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0024_auto_20190328_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceccmenu',
            name='season',
        ),
        migrations.AddField(
            model_name='ceccmenu',
            name='season2',
            field=models.CharField(choices=[('ASPR', 'Spring'), ('BSSM', 'Spring/Summer'), ('CSUM', 'Summer'), ('DAUW', 'Autumn/Winter')], default='ASPR', max_length=4),
        ),
    ]
