# Generated by Django 2.1.4 on 2020-08-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cecc', '0025_auto_20200822_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ceccmenu',
            old_name='season2',
            new_name='season',
        ),
    ]
