# Generated by Django 2.1.4 on 2020-08-24 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answerset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(default='NA', max_length=100)),
                ('answer2', models.CharField(default='NA', max_length=100)),
                ('answer3', models.CharField(default='NA', max_length=100)),
                ('answer4', models.CharField(default='NA', max_length=100)),
                ('answer5', models.CharField(default='NA', max_length=100)),
                ('answer6', models.CharField(default='NA', max_length=100)),
                ('answer7', models.CharField(default='NA', max_length=100)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
