# Generated by Django 2.1.4 on 2020-08-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizthing', '0003_answerset_answer8'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerset',
            name='point1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answerset',
            name='point2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answerset',
            name='point3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answerset',
            name='point4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answerset',
            name='point5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answerset',
            name='point6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answerset',
            name='point7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answerset',
            name='point8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answerset',
            name='roundno',
            field=models.IntegerField(default=1),
        ),
    ]
