# Generated by Django 2.1.4 on 2020-08-29 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizthing', '0004_auto_20200829_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='teamproxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(default='NA', max_length=100)),
                ('points', models.IntegerField(default=11)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='answerset',
            name='roundno',
            field=models.IntegerField(default=11),
        ),
    ]
