# Generated by Django 2.1.4 on 2020-09-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizthing', '0005_auto_20200829_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerset',
            name='roundno',
            field=models.IntegerField(default=1),
        ),
    ]
