# Generated by Django 2.0.2 on 2020-11-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizthing', '0006_auto_20200926_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamproxy',
            name='teamcolor',
            field=models.CharField(default='#888888', max_length=100),
        ),
    ]
